"""
    CorePotts

Numerical cellular Potts solvers on KernelAbstractions: the analogue of OrdinaryDiffEq for
the Potts ecosystem. Models are plain Julia functions (`CPMFunction`), either hand-written
or generated by the symbolic layer in `Potts`. No Symbolics dependency.
"""
module CorePotts

using Adapt: Adapt
using Atomix: Atomix
using CommonSolve: CommonSolve, init, solve, solve!, step!
using KernelAbstractions: KernelAbstractions, @kernel, @index, @Const, @localmem, @synchronize, CPU
using SciMLBase: SciMLBase, remake, reinit!, u_modified!, EnsembleProblem, EnsembleSerial, EnsembleThreads,
    DiscreteCallback, CallbackSet, terminate!
using Serialization: Serialization
using SymbolicIndexingInterface: SymbolicIndexingInterface, getu, setu, getp, setp

export Lattice, Periodic, Closed, nsites, Moore, VonNeumann, NeighborOrder, Ball, Stencil,
    Square, Hexagonal, Hex, embed, embed_covariance, centroid_position,
    Weighted, OnIndices, relation, AllMobile, MaskMobility, is_mobile, in_domain, host_lattice
export CPMState, ownership, cell_kinds, cell_generations, volumes, initial_state, Proposal, Footprint, CPMFunction, commit_volume!,
    contact_delta, volume_delta, surface_change, surface_delta, commit_surface!,
    recompute_surface, site_delta
export init_moments, commit_moments!, centroid, centroid_shift, covariance,
    principal_moments, shape, major_length, major_length_after, min_image
export commit_site_sum!, recompute_site_sum, commit_site_min!, recompute_site_min!
export Phases, SitePhase, CellPhase, ModelPhase, CopyPhase, HistoryPush, history_buffer, history_slot,
    clear_on_copy!
export is_extension, is_retraction, chemotaxis_delta, saturating, saturating_linear,
    neighborhood_mean, MeanFold, ArithmeticMean, GeometricMean, Log1pGeometricMean,
    local_components, locally_connected, ring_arcs, ring_cells, forbid_extinction
export is_boundary_site, count_neighbors, CellReduce, ContactGraph, contact_graph,
    neighbors, contact, empty_contacts, ContactPhase, contact_slot, contact_measure
export Lifecycle, EVENT_NONE, EVENT_DIVIDE, EVENT_DIVIDE_CLUSTER, EVENT_REMOVE, EVENT_TRANSITION, AlongMinorAxis,
    AlongMajorAxis, RandomPlane, along_minor_axis, along_major_axis, random_plane,
    principal_axis, rebuild_trackers!, with_capacity
export empty_links, linked, link_count, link_slot, add_link!, remove_link!, remove_incident!,
    centroid_distance, link_delta, link_claims, HostPhase
export cluster_of, same_cluster, init_clusters, recompute_cluster_volume,
    recompute_cluster_surface, commit_cluster_volume!, cluster_volume_delta,
    cluster_surface_change, cluster_surface_delta, commit_cluster_surface!, cluster_claims
export FieldStep, laplacian, gradient, owner_kind, stable_substeps
export Metropolis, Barker, SequentialCPM, CheckerboardCPM
export PottsProblem, PottsIntegrator, PottsSolution, current_state, refresh_frozen!, frozen_sites, StateIndex, getu, setu, getp, setp
export init, solve, solve!, step!, remake, CPU
# SciML ensembles and callbacks, as solver packages re-export them
export EnsembleProblem, EnsembleSerial, EnsembleThreads, DiscreteCallback, CallbackSet, terminate!, u_modified!
export PottsCheckpoint, checkpoint, save_checkpoint, load_checkpoint, reinit!
export read_piff, write_piff
# Public but not exported: generic lattice and randomness primitives for hand-written models
# and generated code, and the frozen-mask hooks a model system extends (ExplicitImports
# checks qualified accesses against this list).
public coordinates, shift, linear_index, draw, uniform, radius, weight, RNGKey, frozen_varies, frozen_kinds

include("rng.jl")
include("lattice.jl")
include("piff.jl")
include("model.jl")
include("geometry.jl")
include("phases.jl")
include("transfers.jl")
include("fields.jl")
include("drives.jl")
include("spatial.jl")
include("relationships.jl")
include("compartments.jl")
include("lifecycle.jl")
include("lifecycle_device.jl")
include("trackers.jl")
include("algorithms.jl")
include("sequential.jl")
include("checkerboard.jl")
include("problem.jl")
include("checkpoint.jl")

end
