"""
    CorePotts

Numerical cellular Potts solvers on KernelAbstractions: the analogue of OrdinaryDiffEq for
the Potts ecosystem. Models are plain Julia functions (`CPMFunction`), either hand-written
or generated by the symbolic layer in `Potts`. No Symbolics dependency.
"""
module CorePotts

using Adapt: Adapt
using Atomix: Atomix
using CommonSolve: CommonSolve, init, solve, solve!, step!
using KernelAbstractions: KernelAbstractions, @kernel, @index, @Const, CPU
using SciMLBase: SciMLBase, remake

export Lattice, Periodic, Closed, nsites, Moore, VonNeumann, NeighborOrder, Ball, Stencil,
    Weighted, relation
export CPMState, initial_state, Proposal, Footprint, CPMFunction, commit_volume!,
    contact_delta, volume_delta, surface_change, surface_delta, commit_surface!,
    recompute_surface, site_delta
export init_moments, commit_moments!, centroid, centroid_shift, covariance,
    principal_moments, shape, min_image
export commit_site_sum!, recompute_site_sum, commit_site_min!, recompute_site_min!
export Phases, SitePhase, CellPhase, CopyPhase, HistoryPush, history_buffer, history_slot,
    clear_on_copy!
export Metropolis, Barker, SequentialCPM, CheckerboardCPM
export CPMProblem, PottsIntegrator, PottsSolution, current_state
export init, solve, solve!, step!, remake, CPU

include("rng.jl")
include("lattice.jl")
include("model.jl")
include("geometry.jl")
include("phases.jl")
include("trackers.jl")
include("algorithms.jl")
include("sequential.jl")
include("checkerboard.jl")
include("problem.jl")

end
