"""
    CorePotts

Numerical cellular Potts solvers on KernelAbstractions: the analogue of OrdinaryDiffEq for
the Potts ecosystem. Models are plain Julia functions (`CPMFunction`), either hand-written
or generated by the symbolic layer in `Potts`. No Symbolics dependency.
"""
module CorePotts

using Adapt: Adapt
using Atomix: Atomix
using CommonSolve: CommonSolve, init, solve, solve!, step!
using KernelAbstractions: KernelAbstractions, @kernel, @index, @Const, CPU
using SciMLBase: SciMLBase, remake, reinit!
using Serialization: Serialization

export Lattice, Periodic, Closed, nsites, Moore, VonNeumann, NeighborOrder, Ball, Stencil,
    Weighted, relation, AllMobile, MaskMobility, is_mobile
export CPMState, ownership, cell_kinds, cell_generations, volumes, initial_state, Proposal, Footprint, CPMFunction, commit_volume!,
    contact_delta, volume_delta, surface_change, surface_delta, commit_surface!,
    recompute_surface, site_delta
export init_moments, commit_moments!, centroid, centroid_shift, covariance,
    principal_moments, shape, min_image
export commit_site_sum!, recompute_site_sum, commit_site_min!, recompute_site_min!
export Phases, SitePhase, CellPhase, CopyPhase, HistoryPush, history_buffer, history_slot,
    clear_on_copy!
export is_extension, is_retraction, chemotaxis_delta, act_mean, act_delta,
    locally_connected, merks_connectivity, forbid_extinction
export is_boundary_site, count_neighbors, CellReduce, ContactGraph, contact_graph,
    neighbors, contact, empty_contacts, ContactPhase, contact_slot, contact_measure
export Lifecycle, EVENT_NONE, EVENT_DIVIDE, EVENT_REMOVE, EVENT_TRANSITION, AlongMinorAxis,
    AlongMajorAxis, RandomPlane, along_minor_axis, along_major_axis, random_plane,
    principal_axis, rebuild_trackers!, with_capacity
export empty_links, linked, link_count, link_slot, add_link!, remove_link!, remove_incident!,
    centroid_distance, link_delta, link_claims, HostPhase
export FieldStep, laplacian, gradient, owner_kind, stable_substeps
export Metropolis, Barker, SequentialCPM, CheckerboardCPM
export CPMProblem, PottsIntegrator, PottsSolution, current_state
export init, solve, solve!, step!, remake, CPU
export PottsCheckpoint, checkpoint, save_checkpoint, load_checkpoint, reinit!

include("rng.jl")
include("lattice.jl")
include("model.jl")
include("geometry.jl")
include("phases.jl")
include("fields.jl")
include("drives.jl")
include("spatial.jl")
include("relationships.jl")
include("lifecycle.jl")
include("trackers.jl")
include("algorithms.jl")
include("sequential.jl")
include("checkerboard.jl")
include("problem.jl")
include("checkpoint.jl")

end
