# Continuous fields on the lattice: finite-difference primitives and explicit-rate steps
# (ROADMAP M2.4, D-033). A field is a site array of floats in `st.site`; its PDE is a rate
# function generated by the symbolic layer from MTK syntax (`D(c) ~ …`) or written by hand.
#
# Boundaries: periodic axes wrap; closed axes are zero-flux (the missing neighbour mirrors
# the site itself). Spacing `h` is per axis and comes from `ctx.spacing` (typed by the user,
# so Float32 spacing keeps a model device-portable).

@inline _unit(::Val{N}, d, s) where {N} = ntuple(k -> Int32(k == d ? s : 0), Val(N))

@inline spacing(ctx) = haskey(ctx, :spacing) ? ctx.spacing : _ones(ctx.lattice)
@inline _ones(::Lattice{N}) where {N} = ntuple(_ -> 1, Val(N))

# Per-face boundary conditions on closed axes: `bc[d] = (low, high)`, each `nothing`
# (zero flux: the ghost mirrors the site) or a number (Dirichlet: the ghost holds the value
# so the face value is reached midway, i.e. ghost = 2·value − c[x]).
@inline _ghost(ci, ::Nothing) = ci
@inline _ghost(ci, v) = 2 * oftype(ci, v) - ci
@inline _face(::Nothing, d, side) = nothing
@inline _face(bc, d, side) = @inbounds bc[d][side]

@inline function _neighbors_along(c, lat::Lattice{N}, x, i, d, bc = nothing) where {N}
    in1, y1 = shift(lat, x, _unit(Val(N), d, 1))
    in2, y2 = shift(lat, x, _unit(Val(N), d, -1))
    ci = @inbounds c[i]
    up = in1 ? @inbounds(c[linear_index(lat, y1)]) : _ghost(ci, _face(bc, d, 2))
    dn = in2 ? @inbounds(c[linear_index(lat, y2)]) : _ghost(ci, _face(bc, d, 1))
    return up, ci, dn
end

"""
    laplacian(c, ctx, i; h = spacing(ctx), bc = nothing)

Second-order `Σ_d (c[x+e_d] − 2c[x] + c[x−e_d]) / h_d²` at site `i`. On closed axes
`bc = ((low₁, high₁), …)` selects zero flux (`nothing`, default) or a Dirichlet value per face.
"""
@inline function laplacian(c, ctx, i; h = spacing(ctx), bc = nothing)
    lat = ctx.lattice
    x = coordinates(lat, i)
    acc = zero(eltype(c))
    for d in 1:ndims(lat)
        up, ci, dn = _neighbors_along(c, lat, x, i, d, bc)
        acc += (up - 2ci + dn) / h[d]^2
    end
    return acc
end

"""
    gradient(c, ctx, i; h = spacing(ctx), bc = nothing) -> NTuple{N}

Central-difference gradient at site `i` (per-face `bc` as in `laplacian`).
"""
@inline function gradient(c, ctx, i; h = spacing(ctx), bc = nothing)
    lat = ctx.lattice
    x = coordinates(lat, i)
    return ntuple(Val(ndims(lat))) do d
        up, _, dn = _neighbors_along(c, lat, x, i, d, bc)
        (up - dn) / (2 * h[d])
    end
end

"""Kind of the cell owning site `i` (`0` for the medium)."""
@inline owner_kind(st, i) = (c = @inbounds st.σ[i]; c == 0 ? Int32(0) : @inbounds st.cell.kind[c])

"""
    FieldStep((:site, :c) => (:site, :c_next), rate; dt = 1, substeps = 1, lower = nothing)

Explicit Euler for `∂c/∂t = rate(st, p, ctx, key, mcs, i, c)` over one MCS of length `dt`,
in `substeps` equal steps, optionally clipped below at `lower` after each step (legacy
Potts clips concentrations at 0). Each step writes the scratch array and publishes it, so the
rate function sees a consistent field (bulk-synchronous). Stability of diffusion needs
`dt/substeps · D · Σ_d 2/h_d² ≤ 1`; see `stable_substeps`.
"""
struct FieldStep{F <: Part, S <: Part, R, T, L}
    field::F
    scratch::S
    rate::R
    dt::T
    substeps::Int
    lower::L
end
function FieldStep(pair::Pair, rate; dt = 1.0, substeps::Integer = 1, lower = nothing)
    substeps >= 1 || throw(ArgumentError("substeps must be ≥ 1"))
    return FieldStep(Part(pair.first), Part(pair.second), rate, dt, Int(substeps), lower)
end

@inline _clip(v, ::Nothing) = v
@inline _clip(v, lower) = max(v, oftype(v, lower))

@kernel function _field_step_kernel!(rate, cn, @Const(c), st, p, ctx, key, mcs, h, lower)
    i = @index(Global, Linear)
    @inbounds cn[i] = _clip(c[i] + h * rate(st, p, ctx, key, mcs, i, c), lower)
end

function (ph::FieldStep{F, S, R})(st, p, ctx, key, mcs, backend) where {F, S, R}
    c, cn = ph.field(st), ph.scratch(st)
    n = length(c)
    h = eltype(c)(ph.dt / ph.substeps)
    kernel = _field_step_kernel!(backend)
    for _ in 1:ph.substeps
        kernel(ph.rate, cn, c, st, p, ctx, key, mcs, h, ph.lower; ndrange = n,
            workgroupsize = _phase_groupsize(backend, n))
        copyto!(c, cn)
    end
    return 2 * ph.substeps
end

"""Smallest substep count keeping explicit diffusion stable: `dt·D·Σ 2/h_d² / substeps ≤ 1`."""
stable_substeps(D, dt, h) = max(1, ceil(Int, dt * D * sum(x -> 2 / x^2, h)))
