# Continuous fields on the lattice: finite-difference primitives and explicit-rate steps
# (ROADMAP M2.4, D-033). A field is a site array of floats in `st.site`; its PDE is a rate
# function generated by the symbolic layer from MTK syntax (`D(c) ~ …`) or written by hand.
#
# Boundaries: periodic axes wrap; closed axes are zero-flux (the missing neighbour mirrors
# the site itself). Spacing `h` is per axis and comes from `ctx.spacing` (typed by the user,
# so Float32 spacing keeps a model device-portable).

@inline _unit(::Val{N}, d, s) where {N} = ntuple(k -> Int32(k == d ? s : 0), Val(N))

@inline spacing(ctx) = haskey(ctx, :spacing) ? ctx.spacing : _ones(ctx.lattice)
@inline _ones(::Lattice{N}) where {N} = ntuple(_ -> 1, Val(N))

# Per-face boundary conditions on closed axes: `bc[d] = (low, high)`, each `nothing`
# (zero flux: the ghost mirrors the site), a number (Dirichlet: the ghost holds the value
# so the face value is reached midway, i.e. ghost = 2·value − c[x]) or a `GhostFace`.
"""
    GhostFace(dirichlet::Bool, value)

One face of a `bc` (`laplacian`, `gradient`) as a single concrete type: `dirichlet = true` is
a Dirichlet face of value `value` (the ghost is `2·value − c`), `false` zero flux (the ghost
mirrors the site; `value` unused). A `bc` of `GhostFace{T}`s only is homogeneous, so a kernel
indexes it per axis without a type union (generated code, and device kernels, use it).
"""
struct GhostFace{T}
    dirichlet::Bool
    value::T
end
@inline _ghost(ci, ::Nothing) = ci
@inline _ghost(ci, f::GhostFace) = f.dirichlet ? 2 * oftype(ci, f.value) - ci : ci
@inline _ghost(ci, v) = 2 * oftype(ci, v) - ci
@inline _face(::Nothing, d, side) = nothing
@inline _face(bc, d, side) = @inbounds bc[d][side]

@inline function _neighbors_along(c, lat::Lattice{N}, x, i, d, bc = nothing) where {N}
    e1, e2 = _unit(Val(N), d, 1), _unit(Val(N), d, -1)
    in1, y1 = shift(lat, x, e1)
    in2, y2 = shift(lat, x, e2)
    ci = @inbounds c[i]
    # face values apply at the lattice faces; the edge of an irregular domain is zero flux
    up = in1 ? @inbounds(c[linear_index(lat, y1)]) : _within_faces(lat, x, e1) ? ci : _ghost(ci, _face(bc, d, 2))
    dn = in2 ? @inbounds(c[linear_index(lat, y2)]) : _within_faces(lat, x, e2) ? ci : _ghost(ci, _face(bc, d, 1))
    return up, ci, dn
end

"""
    laplacian(c, ctx, i; h = spacing(ctx), bc = nothing)

Second-order `Σ_d (c[x+e_d] − 2c[x] + c[x−e_d]) / h_d²` at site `i`. On closed axes
`bc = ((low₁, high₁), …)` selects zero flux (`nothing`, default) or a Dirichlet value per face
(a number), or either as a [`GhostFace`](@ref).
"""
@inline laplacian(c, ctx, i; h = spacing(ctx), bc = nothing) = _laplacian(ctx.lattice, c, ctx, i, h, bc)
@inline function _laplacian(lat::Lattice, c, ctx, i, h, bc)
    x = coordinates(lat, i)
    acc = zero(eltype(c))
    for d in 1:ndims(lat)
        up, ci, dn = _neighbors_along(c, lat, x, i, d, bc)
        acc += (up - 2ci + dn) / h[d]^2
    end
    return acc
end

"""
    gradient(c, ctx, i; h = spacing(ctx), bc = nothing) -> NTuple{N}

Central-difference gradient at site `i` (per-face `bc` as in `laplacian`).
"""
@inline gradient(c, ctx, i; h = spacing(ctx), bc = nothing) = _gradient(ctx.lattice, c, ctx, i, h, bc)
@inline function _gradient(lat::Lattice, c, ctx, i, h, bc)
    x = coordinates(lat, i)
    return ntuple(Val(ndims(lat))) do d
        up, _, dn = _neighbors_along(c, lat, x, i, d, bc)
        (up - dn) / (2 * h[d])
    end
end

# Hexagonal lattices: the six nearest neighbours at unit distance (spacing `h[1]`, isotropic).
# Δc ≈ 2/(3h²) Σ (c_n − c), ∇c ≈ 1/(3h) Σ (c_n − c) ê_n; missing neighbours (closed faces,
# the domain edge) mirror the site (zero flux; per-face Dirichlet values are square-only).
const _HEX6 = ((Int32(1), Int32(0)), (Int32(-1), Int32(0)), (Int32(0), Int32(1)),
    (Int32(0), Int32(-1)), (Int32(1), Int32(-1)), (Int32(-1), Int32(1)))
@inline function _hex_value(c, lat, x, ci, o)
    inside, y = shift(lat, x, o)
    return inside ? @inbounds(c[linear_index(lat, y)]) : ci
end
@inline function _laplacian(lat::Lattice{2, M, Hexagonal}, c, ctx, i, h, bc) where {M}
    x = coordinates(lat, i)
    ci = @inbounds c[i]
    acc = zero(ci)
    for o in _HEX6
        acc += _hex_value(c, lat, x, ci, o) - ci
    end
    return 2 * acc / (3 * h[1]^2)
end
@inline function _gradient(lat::Lattice{2, M, Hexagonal}, c, ctx, i, h, bc) where {M}
    x = coordinates(lat, i)
    ci = @inbounds c[i]
    gx = zero(ci); gy = zero(ci)
    for o in _HEX6
        e = embed(lat, (oftype(ci, o[1]), oftype(ci, o[2])))
        dv = _hex_value(c, lat, x, ci, o) - ci
        gx += dv * e[1]; gy += dv * e[2]
    end
    return (gx / (3 * h[1]), gy / (3 * h[1]))
end

"""Kind of the cell owning site `i` (`0` for the medium)."""
@inline owner_kind(st, i) = (c = @inbounds st.σ[i]; c == 0 ? Int32(0) : @inbounds st.cell.kind[c])

"""
    FieldStep((:site, :c) => (:site, :c_next), rate; dt = 1, substeps = 1, lower = nothing, clamp = nothing)

Explicit Euler for `∂c/∂t = rate(st, p, ctx, key, mcs, i, c)` over one MCS of length `dt`,
in `substeps` equal steps (a number, or a function of the parameters `p -> n` evaluated
each MCS, so a `remake` with a larger diffusion coefficient stays stable), optionally clipped below at `lower` after each step (legacy
Potts clips concentrations at 0). Each step writes the scratch array and publishes it, so the
rate function sees a consistent field (bulk-synchronous). Explicit Euler is stable when
`dt/substeps · (D · Σ_d 4/h_d² + k) ≤ 2`, with `k` a bound on the reaction's `|∂f/∂c|`; see
`stable_substeps`.

`clamp` (a masked Dirichlet condition, a node value) is `nothing` or a callable
`clamp(st, p, ctx, key, mcs, i, v) -> v′` applied to every substep's new value at site `i`,
after the `lower` clip: it returns the clamped value where its mask holds and `v` elsewhere.
It is evaluated on the state the substep reads (σ, kinds and variables do not change during
a field step), in the same kernel as the step, so a clamp costs no launch; [`FieldClamp`](@ref)
applies it to a state outside a step (the initial state).
"""
struct FieldStep{F <: Part, S <: Part, R, T, N, L, C}
    field::F
    scratch::S
    rate::R
    dt::T
    substeps::N          # an Int, or `p -> Int` (from the current parameters, host-side)
    lower::L
    clamp::C
end
FieldStep(field::Part, scratch::Part, rate, dt, substeps, lower) = FieldStep(field, scratch, rate, dt, substeps, lower, nothing)
function FieldStep(pair::Pair, rate; dt = 1.0, substeps = 1, lower = nothing, clamp = nothing)
    substeps isa Integer && (substeps >= 1 || throw(ArgumentError("substeps must be ≥ 1")))
    return FieldStep(Part(pair.first), Part(pair.second), rate, dt,
        substeps isa Integer ? Int(substeps) : substeps, lower, clamp)
end

@inline _substeps(n::Int, p) = n
_substeps(f::F, p) where {F} = max(1, Int(f(p)))

@inline _clip(v, ::Nothing) = v
@inline _clip(v, lower) = max(v, oftype(v, lower))

@inline function _field_step_body!(i, rate, cn, c, st, p, ctx, key, mcs, h, lower)
    # outside the lattice domain the field is inert (neighbours never read it)
    @inbounds cn[i] = in_domain(ctx.lattice, i) ? _clip(c[i] + h * rate(st, p, ctx, key, mcs, i, c), lower) : c[i]
end
# with a clamp: the clipped value, then the mask (a mask value below `lower` wins)
@inline function _field_step_clamp_body!(i, rate, cn, c, st, p, ctx, key, mcs, h, lower, clamp)
    @inbounds cn[i] = in_domain(ctx.lattice, i) ?
                      clamp(st, p, ctx, key, mcs, i, _clip(c[i] + h * rate(st, p, ctx, key, mcs, i, c), lower)) : c[i]
end

_step_args(::Nothing, rate, cn, c, st, p, ctx, key, mcs, h, lower) = (rate, cn, c, st, p, ctx, key, mcs, h, lower)
_step_args(clamp, rate, cn, c, st, p, ctx, key, mcs, h, lower) = (rate, cn, c, st, p, ctx, key, mcs, h, lower, clamp)
_step_body(::Nothing) = _field_step_body!
_step_body(clamp) = _field_step_clamp_body!

function (ph::FieldStep{F, S, R})(st, p, ctx, key, mcs, backend) where {F, S, R}
    c, cn = ph.field(st), ph.scratch(st)
    n = length(c)
    nsub = _substeps(ph.substeps, p)
    h = eltype(c)(ph.dt / nsub)
    for _ in 1:nsub
        _launch(_step_body(ph.clamp), backend, n, _step_args(ph.clamp, ph.rate, cn, c, st, p, ctx, key, mcs, h, ph.lower))
        _device_copy!(backend, c, cn)        # a kernel: no GPU wait (P6.0v8)
    end
    return 2 * nsub
end

"""
    FieldClamp((:site, :c), clamp)

A phase applying a [`FieldStep`](@ref) `clamp` to the field as it is: `c[i] = clamp(st, p,
ctx, key, mcs, i, c[i])` at every site of the domain (one kernel). Potts puts it in `at_init`,
so a fresh initial state satisfies the masked conditions; `init` from a checkpoint skips it
(the restored state continues its run exactly).
"""
struct FieldClamp{F <: Part, C}
    field::F
    clamp::C
end
FieldClamp(path::Tuple{Symbol, Symbol}, clamp) = FieldClamp(Part(path), clamp)

@inline _field_clamp_body!(i, clamp, c, st, p, ctx, key, mcs) =
    (in_domain(ctx.lattice, i) && @inbounds(c[i] = clamp(st, p, ctx, key, mcs, i, c[i])); nothing)   # i ≤ nsites = length(c)

function (ph::FieldClamp)(st, p, ctx, key, mcs, backend)
    c = ph.field(st)
    _launch(_field_clamp_body!, backend, length(c), (ph.clamp, c, st, p, ctx, key, mcs))
    return 1
end

# The at-init phases of a state that is not fresh (a checkpoint restore, `Potts.anneal`'s
# per-MCS refresh): the derived refreshes without the field clamps, which hold on a fresh
# initial state only (D-145)
_derived(t::Tuple) = filter(ph -> !(ph isa FieldClamp), t)

"""
    stable_substeps(D, dt, h, k = 0) -> Int

Substep count for explicit Euler on `∂c/∂t = D Δc + f(c)` over a step of length `dt`, on a
lattice with spacings `h` (a tuple, one per axis), when `|∂f/∂c| ≤ k`: the smallest `n ≥ 1`
with

    ρ = dt/n · (D · Σ_d 4/h_d² + k) ≤ 1.8.

`D · Σ_d 4/h_d² + k` bounds the spectral radius of the linearized step operator (the
lattice checkerboard is the fastest diffusion mode), and explicit Euler is stable for
`ρ ≤ 2`. The margin to 1.8 damps every mode by at least 20 % per substep, so grid-scale
noise is removed rather than left ringing at the edge of stability, at about 10 % more
substeps than the edge count. The bound holds on square lattices with any boundary; on
hexagonal lattices (fastest mode `6D/h²`) it is conservative.
"""
stable_substeps(D, dt, h, k = 0) = max(1, ceil(Int, dt * (D * sum(x -> 4 / x^2, h) + k) / 1.8))
