# SciML interface: problem → init → step!/solve!, with CommonSolve dispatch so that
# `solve(prob, alg)`, `EnsembleProblem`, callbacks-by-integrator and `remake` behave as in
# the rest of SciML. Time is the integer MCS.

const STATUS_NONFINITE = UInt32(1)

"""
    PottsProblem(f::CPMFunction, u0::CPMState, lattice, tspan, p;
                 contact = Moore(1), proposal = VonNeumann(1), relations = (;), seed = 0,
                 replica = 0, repeat = 0)

A cellular Potts problem. `tspan = (t0, t1)` in MCS. `frozen` (a Bool mask) marks sites
that never change owner and never donate (walls, obstacles); an MCS is one attempt per
mobile site. `spacing` (per-axis lattice spacing,
default 1) is exposed as `ctx.spacing` to field primitives; give it in the model's float
type (Float32 for Metal). `contact` and the named `relations`
(e.g. `(; surface = Moore(1))`) are resolved on `lattice` and exposed to the model's
functions as `ctx.contact`, `ctx.surface`, …. `proposal` is the model's copy neighbourhood,
used by algorithms constructed without one (`SequentialCPM()`). `p` is any isbits parameter object (a `NamedTuple`, or the `PottsParameters`
generated by the symbolic layer); changing it with `remake` never recompiles.
"""
struct PottsProblem{F <: CPMFunction, S <: CPMState, L <: Lattice, R, Q, RS, H, FZ, P} <:
       SciMLBase.AbstractSciMLProblem
    f::F
    u0::S
    lattice::L
    contact::R
    proposal::Q                         # a neighbourhood spec, resolved at `init`
    relations::RS
    spacing::H
    frozen::FZ
    tspan::Tuple{Int, Int}
    p::P
    seed::UInt64
    replica::UInt32
    repeat::UInt32
end

function PottsProblem(f::CPMFunction, u0::CPMState, lattice::Lattice, tspan, p;
        contact = Moore(1), proposal = VonNeumann(1), relations = (;), spacing = nothing,
        frozen = nothing, seed = 0, replica = 0, repeat = 0)
    size(u0.σ) == lattice.dims ||
        throw(ArgumentError("state size $(size(u0.σ)) ≠ lattice $(lattice.dims)"))
    t0, t1 = Int.(tspan)
    0 <= t0 <= t1 <= typemax(UInt32) ||
        throw(ArgumentError("tspan must satisfy 0 ≤ t0 ≤ t1 ≤ 2^32 - 1"))
    any(in((:contact, :proposal, :lattice, :mobility, :spacing)), keys(relations)) &&
        throw(ArgumentError("relation names `contact`, `proposal`, `lattice`, `mobility`, `spacing` are reserved"))
    rs = map(r -> relation(r, lattice), NamedTuple(relations))
    h = spacing === nothing ? nothing : Tuple(spacing)
    h === nothing || (length(h) == ndims(lattice) && all(x -> x > 0, h)) ||
        throw(ArgumentError("spacing must be $(ndims(lattice)) positive numbers"))
    frozen === nothing || size(frozen) == lattice.dims ||
        throw(ArgumentError("frozen mask has size $(size(frozen)), lattice $(lattice.dims)"))
    kinds = frozen_kinds(f.sys)
    if kinds !== nothing                            # the standard rule decides the mask
        rule = _standard_frozen(kinds, u0)
        dom(m) = lattice.mask === nothing ? m : m .| .!lattice.mask
        frozen === nothing || dom(frozen) == dom(rule) || throw(ArgumentError(
            "a model with frozen kinds $kinds derives its frozen mask from the state; a " *
            "`frozen` mask that differs from it cannot be combined with them (give the " *
            "obstacle sites to a cell of a frozen kind instead)"))
        frozen = rule
    end
    if lattice.mask !== nothing                     # outside the domain: medium, never mobile
        all(i -> lattice.mask[i] || u0.σ[i] == 0, eachindex(u0.σ)) ||
            throw(ArgumentError("sites outside the lattice domain must belong to the medium (0)"))
        frozen = frozen === nothing ? .!lattice.mask : (frozen .| .!lattice.mask)
    end
    relation(proposal, lattice)                     # validate now; resolved again at `init`
    return PottsProblem(f, u0, lattice, relation(contact, lattice), proposal, rs, h, frozen, (t0, t1), p,
        UInt64(seed), UInt32(replica), UInt32(repeat))
end

# Hooks for the symbolic layer: translate parameter maps / operating points given to
# `remake` into the problem's parameter object and state (identity here).
remake_parameters(sys, prob, p) = p
remake_state(sys, prob, u0) = u0
"""
    frozen_kinds(sys)

The kinds whose cells' sites are frozen, as a tuple of `Int32`, or `nothing` (the default).
A system that returns kinds uses the standard rule (D-081): a site is frozen when its
owner's kind is listed or it lies outside the lattice domain. The rule builds the
problem's mask (`PottsProblem`, `remake`, checkpoint resume) and is recomputed on the
integrator's backend after lifecycle events. A problem with frozen kinds takes no other
`frozen` mask.
"""
frozen_kinds(sys) = nothing

"""
    frozen_varies(sys)

Whether the frozen mask follows the state during a run. Default: `frozen_kinds(sys) !==
nothing`. `false` means a static mask (none, a domain, a user `frozen`), never recomputed.
"""
frozen_varies(sys) = frozen_kinds(sys) !== nothing

"""
    remake_frozen(sys, prob, u0)

The frozen mask of a remade or reinitialized state `u0`: the standard rule when
`frozen_kinds(sys)` names kinds, else `prob.frozen` (a static mask).

A custom rule overrides this method **and must also define `frozen_varies(sys) = true`**;
without it the integrator treats the mask as static and never recomputes it (no error).
A custom rule runs on a host copy of the state at every refresh.
"""
remake_frozen(sys, prob, u0) = (k = frozen_kinds(sys)) === nothing ? prob.frozen : _standard_frozen(k, u0)

# A custom `remake_frozen` without `frozen_varies(sys) = true` gives a static mask: say so.
function _check_frozen_hooks(sys)
    frozen_varies(sys) && return nothing
    which(remake_frozen, Tuple{typeof(sys), Any, Any}).module === CorePotts && return nothing
    @warn "`remake_frozen` is overridden for $(typeof(sys)) but `frozen_varies(sys)` is false: the " *
          "frozen mask stays static during a run. Define `CorePotts.frozen_varies(::$(typeof(sys))) = true`." maxlog = 1
    return nothing
end

# the standard rule on a host state (without the domain, which `PottsProblem` adds)
function _standard_frozen(kinds, u)
    k = Array(u.cell.kind)
    return map(s -> s != 0 && _in_kinds(k[s], kinds), Array(u.σ))
end
# `remake` keywords beyond the fixed ones (a symbolic layer's problem-construction keywords,
# e.g. Potts' solvers): `(f, u0)`, a new `f` built from them and `prob.u0` re-laid out for it
# if its state layout depends on them (values kept); everything else is kept
function remake_function(sys, prob; kwargs...)
    throw(ArgumentError("remake: unknown keyword$(length(kwargs) == 1 ? "" : "s") " *
                        "$(join(("`$k`" for k in keys(kwargs)), ", "))"))
end

function SciMLBase.remake(prob::PottsProblem; f = prob.f, u0 = prob.u0, tspan = prob.tspan,
        p = prob.p, seed = prob.seed, replica = prob.replica, repeat = prob.repeat, kwargs...)
    relaid = prob.u0
    if !isempty(kwargs)
        f === prob.f || throw(ArgumentError("remake: give `f` or the keywords it is rebuilt from " *
                                            "($(join(("`$k`" for k in keys(kwargs)), ", "))), not both"))
        f, relaid = remake_function(f.sys, prob; kwargs...)
    end
    p === prob.p || (p = remake_parameters(f.sys, prob, p))
    frozen = prob.frozen
    if u0 !== prob.u0
        u0 = remake_state(f.sys, prob, u0)
        frozen = remake_frozen(f.sys, prob, u0)
    else
        u0 = relaid
    end
    return PottsProblem(f, u0, prob.lattice, tspan, p; contact = prob.contact,
        proposal = prob.proposal, relations = prob.relations, spacing = prob.spacing, frozen, seed,
        replica, repeat)
end

Base.@kwdef mutable struct PottsStats
    mcs::Int = 0
    attempts::Int = 0
    accepted::Int = -1          # -1: not counted by this algorithm (checkerboard)
    launches::Int = 0
    refreshes::Int = 0          # frozen-mask recomputations (`refresh_frozen!`)
    lifecycle::LifecycleStats = LifecycleStats()
end

"""
    PottsIntegrator

The integrator for a `PottsProblem`. `t` is the current MCS; `integrator.u` returns a host
copy of the state (synchronizing the device only when accessed). `step!` enqueues one MCS
without synchronizing.
"""
mutable struct PottsIntegrator{Alg, Law, P, S, C, LCC, F, KF, Pa, Ctx, B, CB, MS} <: SciMLBase.DEIntegrator{Alg, false, S, Int}
    const prob::P
    const alg::Alg
    const law::Law
    const state::S
    const cache::C
    const lcache::LCC
    const f::F
    const kf::KF
    p::Pa
    const ctx::Ctx
    const backend::B
    const key::RNGKey
    t::Int
    const tstop::Int
    const saveat::Vector{Int}
    const save_start::Bool
    const save_end::Bool
    const saved_t::Vector{Int}
    const saved_u::Vector{Any}
    retcode::SciMLBase.ReturnCode.T
    const stats::PottsStats
    const callbacks::CB             # tuple of DiscreteCallbacks, checked after every MCS
    nmobile::Int                    # mobile sites: the attempts of one MCS
    const mscratch::MS              # `MobileCounters` of the standard-rule refresh, or nothing
end

# Counts of the standard-rule refresh (D-081). `device` = [lifecycle events, mobile-count
# change, changed sites]: with a lifecycle it is the lifecycle's `count`, so the counts of a
# refresh after an event MCS travel with the next lifecycle read-back (no transfer of their
# own on a device). `pending`: counts not read yet; `stale`: the MCS since then whose
# attempts used the old count (corrected when they arrive).
mutable struct MobileCounters{D}
    const device::D
    const host::Vector{Int32}
    pending::Bool
    stale::Int
end

# Ensemble statistics: totals over trajectories.
function Base.merge(a::PottsStats, b::PottsStats)
    l = LifecycleStats(; (f => getfield(a.lifecycle, f) + getfield(b.lifecycle, f) for f in fieldnames(LifecycleStats))...)
    return PottsStats(; mcs = a.mcs + b.mcs, attempts = a.attempts + b.attempts,
        accepted = (a.accepted < 0 || b.accepted < 0) ? -1 : a.accepted + b.accepted,
        launches = a.launches + b.launches, refreshes = a.refreshes + b.refreshes, lifecycle = l)
end

_to_backend(backend, x) = Adapt.adapt(KernelAbstractions.allocate(backend, Int32, 0) |>
                                      typeof |> _array_adaptor, x)
_array_adaptor(::Type{<:Array}) = Array
_array_adaptor(A::Type) = Base.typename(A).wrapper

"""The copy neighbourhood: the algorithm's if given, else the model's."""
_proposal(alg, prob) = something(alg.proposal, prob.proposal)

function CommonSolve.init(prob::PottsProblem, alg::CPMAlgorithm; backend = CPU(),
        saveat = Int[], save_start = true, save_end = true, checkpoint = nothing,
        callback = nothing)
    if checkpoint !== nothing
        prob = _from_checkpoint(prob, checkpoint)
        integ = init(prob, alg; backend, saveat, save_start, save_end, callback)
        _restore_stats!(integ.stats, checkpoint.stats)
        return integ
    end
    alg isa SequentialCPM && !(backend isa CPU) &&
        throw(ArgumentError("SequentialCPM runs on the host; use CheckerboardCPM on $(typeof(backend))"))
    t0, t1 = prob.tspan
    # SciML convention: a number means "every Δ MCS" from t0 (t0 itself is `save_start`)
    saveat isa Number && (saveat = (t0 + Int(saveat)):Int(saveat):t1)
    outside = filter(t -> !(t0 <= t <= t1), collect(Int, saveat))
    isempty(outside) || @warn "saveat times outside tspan $(prob.tspan) are never reached: $outside"
    lat = prob.lattice
    ctx = (; lattice = _to_backend(backend, lat), proposal = relation(_proposal(alg, prob), lat), contact = prob.contact,
        mobility = _backend_mobility(backend, mobility(prob.frozen, lat)), prob.relations...)
    prob.spacing === nothing || (ctx = merge(ctx, (; spacing = prob.spacing)))
    _preflight(prob, alg, ctx)
    _check_frozen_hooks(prob.f.sys)
    state = _to_backend(backend, deepcopy(prob.u0))
    p = _to_backend(backend, prob.p)
    cache = alg isa CheckerboardCPM ?
            CheckerboardCache(backend, lat, prob.f, ncells(prob.u0), relation(_proposal(alg, prob), lat)) : nothing
    key = RNGKey(prob.seed, prob.replica, prob.repeat)
    lcache = prob.f.lifecycle === nothing ? nothing :
             LifecycleCache(backend, ndims(lat), ncells(prob.u0))
    integ = PottsIntegrator(prob, alg, _device_law(_law(alg, prob.f), backend), state, cache, lcache, prob.f, device_functions(prob.f), p, ctx, backend, key,
        prob.tspan[1], prob.tspan[2], sort!(collect(Int, saveat)), save_start, save_end,
        Int[], Any[], SciMLBase.ReturnCode.Default, PottsStats(), _callbacks(callback),
        prob.frozen === nothing ? nsites(lat) : count(!, prob.frozen), _mobility_scratch(backend, prob, ctx.mobility, lcache))
    integ.stats.launches += _run_phases(prob.f.phases.at_init, integ.state, integ.p, integ.ctx,
        integ.key, integ.t, integ.backend)
    for cb in integ.callbacks
        cb.initialize(cb, integ.state, integ.t, integ)
    end
    save_start && _save!(integ)
    return integ
end

# SciML callbacks: `DiscreteCallback`s (alone or in a `CallbackSet`) are checked at every
# MCS boundary, after the lifecycle and before saving. `condition(u, t, integrator)` and
# `affect!(integrator)` see the live state (`integrator.state`, on the device for GPU
# backends; `integrator.u` is a host copy). Continuous callbacks have no meaning for an
# MCS clock.
_callbacks(::Nothing) = ()
_callbacks(cb::SciMLBase.DiscreteCallback) = (cb,)
function _callbacks(cb::SciMLBase.CallbackSet)
    isempty(cb.continuous_callbacks) ||
        throw(ArgumentError("continuous callbacks are not supported by Potts integrators (time is the integer MCS); use DiscreteCallback"))
    return cb.discrete_callbacks
end
_callbacks(cb) = throw(ArgumentError("unsupported callback $(typeof(cb)); use DiscreteCallback or CallbackSet"))

function _apply_callbacks!(integ::PottsIntegrator)
    for cb in integ.callbacks
        cb.condition(integ.state, integ.t, integ) && cb.affect!(integ)
    end
    return nothing
end

# No derivative to reset: a callback's changes take effect at the next MCS.
SciMLBase.derivative_discontinuity!(::PottsIntegrator, ::Bool) = nothing
# `u_modified!(integ, true)` after writing the state: the frozen mask follows (D-081)
SciMLBase.u_modified!(integ::PottsIntegrator, modified::Bool) = (modified && refresh_frozen!(integ); nothing)

"""
Reject combinations the algorithm cannot execute correctly. The checkerboard stride comes
from the model's declared footprint, so the declared read radius must cover everything
the kernels read: the proposal source and the contact neighborhood.
"""
function _preflight(prob::PottsProblem, alg::CPMAlgorithm, ctx)
    prob.f.lifecycle === nothing || haskey(prob.u0.cell, :m1) ||
        throw(ArgumentError("a lifecycle needs the moment trackers: add `init_moments(σ, lattice, capacity)` to the cell state"))
    haskey(ctx, :surface) && has_origin(ctx.surface) &&
        throw(ArgumentError("the surface relation must not include the origin"))
    # the pair-energy deltas assume unordered bonds: every offset needs its negation
    for name in (:contact, :surface)
        haskey(ctx, name) && !is_symmetric(getfield(ctx, name)) && throw(ArgumentError(
            "the $name relation is not symmetric (each offset needs its negation with the same " *
            "weight); an asymmetric relation gives a ΔH that is not an energy difference"))
    end
    alg isa CheckerboardCPM || return nothing
    need = max(radius(ctx.contact), maximum(radius, values(prob.relations); init = 0))
    have = first(reach(prob.f.footprint, ctx.proposal))
    have >= need || throw(ArgumentError(
        "CheckerboardCPM: the model declares Footprint(read = $have) but its proposal, " *
        "contact and named relations reach distance $need; pass `footprint = Footprint(read = $need)` " *
        "to CPMFunction"))
    return nothing
end

"""
Host snapshot of the current state: independent of the live state on every backend
(`Adapt.adapt(Array, …)` alone would alias host arrays). Synchronizes the device. The live
device state is `integ.state`.
"""
function current_state(integ::PottsIntegrator)
    KernelAbstractions.synchronize(integ.backend)
    return _snapshot(integ.backend, integ.state)
end
_snapshot(backend, st) = Adapt.adapt(Array, st)
_snapshot(::KernelAbstractions.CPU, st) = deepcopy(st)

function Base.getproperty(integ::PottsIntegrator, name::Symbol)
    name === :u && return current_state(integ)
    name === :ps && return SymbolicIndexingInterface.ParameterIndexingProxy(integ)
    return getfield(integ, name)
end

function _save!(integ::PottsIntegrator)
    push!(integ.saved_t, integ.t)
    push!(integ.saved_u, current_state(integ))
    return nothing
end

function _check_status!(integ::PottsIntegrator)
    integ.alg isa CheckerboardCPM || return integ.retcode
    st = _readback(integ.cache.status)
    st != 0 && (integ.retcode = SciMLBase.ReturnCode.Failure)
    return integ.retcode
end

function CommonSolve.step!(integ::PottsIntegrator)
    integ.retcode == SciMLBase.ReturnCode.Default ||
        throw(ArgumentError("integrator finished with retcode $(integ.retcode)"))
    lat = integ.ctx.lattice
    phases = integ.f.phases
    attempts = integ.nmobile                        # this sweep's count (a refresh may change it)
    _count_stale!(integ.mscratch)
    integ.stats.launches += _run_phases(phases.before_mcs, integ.state, integ.p, integ.ctx,
        integ.key, integ.t, integ.backend)
    if integ.alg isa SequentialCPM
        acc, status = sequential_mcs!(integ.state, integ.kf, integ.p, integ.ctx,
            integ.law, integ.key, integ.t)
        integ.stats.accepted = max(integ.stats.accepted, 0) + acc
        status != 0 && (integ.retcode = SciMLBase.ReturnCode.Failure)
    else
        integ.stats.launches += checkerboard_mcs!(integ.state, integ.cache, integ.kf,
            integ.p, integ.ctx, integ.law, integ.key, integ.t)
    end
    integ.stats.launches += _run_phases(phases.after_mcs, integ.state, integ.p, integ.ctx,
        integ.key, integ.t, integ.backend)
    if integ.f.lifecycle !== nothing
        sc = integ.mscratch
        nread = sc !== nothing && sc.pending ? 3 : 1
        launches, events, read = run_lifecycle!(integ.f.lifecycle, integ.lcache, integ.state,
            integ.p, integ.ctx, integ.key, integ.t, integ.backend, integ.stats.lifecycle; nread)
        integ.stats.launches += launches
        read && _take_counts!(integ)                # a deferred refresh's counts, if any
        # a transition, division or removal may move sites into or out of frozen kinds;
        # quiet MCS pay nothing (D-081)
        events && _refresh_frozen!(integ, true)
    end
    integ.stats.launches += _run_phases(phases.end_mcs, integ.state, integ.p, integ.ctx,
        integ.key, integ.t, integ.backend)
    integ.t += 1
    integ.stats.mcs += 1
    integ.stats.attempts += attempts
    isempty(integ.callbacks) || _apply_callbacks!(integ)
    insorted(integ.t, integ.saveat) && (_check_status!(integ); _save!(integ))
    return integ
end

# counters for the standard-rule refresh: only when the mask can change by the standard rule
_mobility_scratch(backend, prob, ::AllMobile, lcache) = nothing
function _mobility_scratch(backend, prob, ::MaskMobility, lcache)
    (frozen_varies(prob.f.sys) && frozen_kinds(prob.f.sys) !== nothing) || return nothing
    lcache === nothing && return MobileCounters(KernelAbstractions.zeros(backend, Int32, 3), zeros(Int32, 3), false, 0)
    return MobileCounters(lcache.count, lcache.host, false, 0)
end

@inline _count_stale!(::Nothing) = nothing
@inline _count_stale!(sc::MobileCounters) = (sc.pending && (sc.stale += 1); nothing)

# apply the counts in `sc.host` (just read) of a pending refresh
function _take_counts!(integ)
    sc = integ.mscratch
    (sc === nothing || !sc.pending) && return nothing
    d = Int(sc.host[2])
    integ.nmobile += d
    integ.stats.attempts += d * sc.stale            # MCS that ran with the old count
    sc.pending = false
    sc.stale = 0
    return nothing
end

# read a pending refresh's counts now (synchronizes; only off the MCS loop)
function _flush_counts!(integ)
    sc = integ.mscratch
    (sc === nothing || !sc.pending) && return nothing
    copyto!(sc.host, sc.device)
    fill!(sc.device, Int32(0))
    _take_counts!(integ)
    return nothing
end

"""
    refresh_frozen!(integrator)

Recompute the frozen-site mask from the integrator's current state. The integrator does
this itself after every MCS with a lifecycle event (transition, division, removal), and
`reinit!` does it for the new state. A `DiscreteCallback` that writes `kind` (or `σ` around
frozen cells) directly in `integrator.state` must call it, or `u_modified!(integrator,
true)`; `set_state!` (`setu`) on `kind` calls it.

Only models whose mask follows the state (`frozen_varies`; Potts: a `[frozen]` kind) do
any work; for a static mask (none, the domain, a user `frozen`) it returns at once. The
standard rule (`frozen_kinds`) runs as one kernel on the integrator's backend; called
directly, it then reads back its counts (one small transfer). A custom rule
(`remake_frozen`) runs on a host copy of the state.

On a device, after the integrator's own refresh on an event MCS, `integrator.nmobile` and
`integrator.stats.attempts` lag by that refresh's change until the next lifecycle read-back
(the mask itself is current at once). `solve!`, `checkpoint` and any direct
`refresh_frozen!` bring them up to date; code that calls `step!` directly and reads them
between those points sees the lagging values.
"""
refresh_frozen!(integ::PottsIntegrator) = (_refresh_frozen!(integ, false); integ)

# `defer`: after a lifecycle event on a device, the counts wait for the next lifecycle
# read-back (the mask itself is current at once: CheckerboardCPM reads only the mask)
function _refresh_frozen!(integ::PottsIntegrator, defer::Bool)
    m = integ.ctx.mobility
    (m isa AllMobile || !frozen_varies(integ.f.sys)) && return nothing
    integ.stats.refreshes += 1
    _refresh_frozen!(integ, m, frozen_kinds(integ.f.sys), defer)
    return nothing
end

# the standard rule: one kernel rewrites the mask and counts the changes on the device
function _refresh_frozen!(integ, m::MaskMobility, kinds::Tuple, defer::Bool)
    sc = integ.mscratch
    defer &= !(integ.backend isa CPU) && integ.lcache !== nothing   # the host reads its own memory at once
    defer || _flush_counts!(integ)
    _launch(_frozen_body!, integ.backend, length(integ.state.σ),
        (m.frozen, sc.device, integ.state.σ, integ.state.cell.kind, kinds, integ.ctx.lattice))
    integ.stats.launches += 1
    if defer
        sc.pending, sc.stale = true, 0
    else
        copyto!(sc.host, sc.device)                 # synchronizes (a no-op copy on the CPU)
        fill!(sc.device, Int32(0))
        integ.nmobile += sc.host[2]
        sc.host[3] > 0 && m.sites !== nothing && _mobile_sites!(m.sites, m.frozen)
    end
    return nothing
end
# a custom rule: `remake_frozen` on a host copy of the state
function _refresh_frozen!(integ, m::MaskMobility, ::Nothing, defer::Bool)
    KernelAbstractions.synchronize(integ.backend)
    u = integ.backend isa CPU ? integ.state : _snapshot(integ.backend, integ.state)
    fz = frozen_sites(integ.prob, u)
    _set_mobility!(m, fz)
    integ.nmobile = count(!, fz)
    return nothing
end

"""
    frozen_sites(prob, u)

The frozen-site mask (a host `Bool` array, or `nothing`) of state `u` for problem `prob`:
the rule the integrator applies at a refresh (`refresh_frozen!`), with the sites outside
the lattice domain. For a model whose mask does not vary it is `prob.frozen`. Use it to
draw a saved state's obstacles.
"""
function frozen_sites(prob::PottsProblem, u)
    sys = prob.f.sys
    frozen_varies(sys) || return prob.frozen
    kinds = frozen_kinds(sys)
    fz = kinds === nothing ? remake_frozen(sys, prob, u) : _standard_frozen(kinds, u)
    m = prob.lattice.mask
    m === nothing && return fz
    return fz === nothing ? .!m : fz .| .!m
end

function CommonSolve.solve!(integ::PottsIntegrator)
    while integ.t < integ.tstop && integ.retcode == SciMLBase.ReturnCode.Default
        step!(integ)
    end
    _flush_counts!(integ)                           # exact `stats.attempts` at the end
    _check_status!(integ)
    if integ.retcode == SciMLBase.ReturnCode.Default
        integ.retcode = SciMLBase.ReturnCode.Success
    end
    integ.save_end && (isempty(integ.saved_t) || last(integ.saved_t) != integ.t) &&
        _save!(integ)
    for cb in integ.callbacks
        cb.finalize(cb, integ.state, integ.t, integ)
    end
    return PottsSolution(integ)
end

SciMLBase.check_error(integ::PottsIntegrator) = integ.retcode
function SciMLBase.terminate!(integ::PottsIntegrator, retcode = SciMLBase.ReturnCode.Terminated)
    integ.retcode = retcode
    return integ
end

# ---------------------------------------------------------------------------------------

"""Saved states at integer MCS. `sol(t)` looks up a saved MCS exactly (no interpolation)."""
struct PottsSolution{S, P, A} <: SciMLBase.AbstractTimeseriesSolution{S, 1, Vector{S}}
    u::Vector{S}
    t::Vector{Int}
    prob::P
    alg::A
    retcode::SciMLBase.ReturnCode.T
    stats::PottsStats
end

function PottsSolution(integ::PottsIntegrator)
    S = isempty(integ.saved_u) ? Any : typeof(first(integ.saved_u))
    return PottsSolution(convert(Vector{S}, integ.saved_u), copy(integ.saved_t),
        integ.prob, integ.alg, integ.retcode, integ.stats)
end

# Integer indexing is by saved state (`sol[end]` is the final state), not RecursiveArrayTools'
# element indexing: a state is a named collection of arrays, not an array.
Base.getindex(sol::PottsSolution, i::Int) = sol.u[i]
Base.getindex(sol::PottsSolution, i::AbstractVector{<:Integer}) = sol.u[i]
Base.firstindex(sol::PottsSolution) = firstindex(sol.u)
Base.lastindex(sol::PottsSolution) = lastindex(sol.u)

function Base.show(io::IO, ::MIME"text/plain", sol::PottsSolution)
    n = length(sol.t)
    println(io, "PottsSolution: retcode ", sol.retcode, ", ", n, " saved state", n == 1 ? "" : "s",
        ", ", sol.stats.mcs, " MCS")
    print(io, "t: ", n <= 12 ? sol.t : "[$(join(sol.t[1:5], ", ")), …, $(join(sol.t[(end - 4):end], ", "))]")
end
Base.show(io::IO, sol::PottsSolution) =
    print(io, "PottsSolution(", sol.retcode, ", ", length(sol.t), " states)")

function (sol::PottsSolution)(t::Integer)
    i = searchsortedfirst(sol.t, t)
    (i <= length(sol.t) && sol.t[i] == t) ||
        throw(ArgumentError("MCS $t was not saved; saved times are $(sol.t)"))
    return sol.u[i]
end

function _restore_stats!(dst::PottsStats, src::PottsStats)
    dst.mcs, dst.attempts, dst.accepted, dst.launches = src.mcs, src.attempts, src.accepted, src.launches
    dst.refreshes = src.refreshes
    for f in fieldnames(LifecycleStats)
        setfield!(dst.lifecycle, f, getfield(src.lifecycle, f))
    end
    return dst
end

# ---------------------------------------------------------------------------------------
# SymbolicIndexingInterface: the symbolic system (if any) is `f.sys`; symbolic layers
# implement the SII queries on it (`sol[x]`, `getp(prob, x)`).

# ---------------------------------------------------------------------------------------
# Ensembles: trajectory `i` is the template with `replica = template.replica + i` and
# `repeat = ctx.repeat - 1` (independent Philox streams, D-005; one compiled model), unless
# the user's `prob_func` already changed the seed or replica.

"""
    EnsembleProblem(prob::PottsProblem; prob_func, output_func, reduction, u_init, safetycopy = false)

A SciML ensemble of Potts runs. Trajectory `i` solves `remake(prob′; replica = prob.replica + i)`,
where `prob′ = prob_func(prob, ctx)` (default: `prob`), so trajectories are independent and
reproducible: trajectory `i` equals `solve(remake(prob; replica = prob.replica + i), alg)`.
"""
function SciMLBase.EnsembleProblem(prob::PottsProblem; prob_func = SciMLBase.DEFAULT_PROB_FUNC,
        safetycopy = false, kwargs...)
    pf = _ReplicaProbFunc(prob_func)
    return invoke(SciMLBase.EnsembleProblem, Tuple{Any}, prob; prob_func = pf, safetycopy, kwargs...)
end

"""
    solve(ens::EnsembleProblem, alg::CPMAlgorithm; backend = CPU(), trajectories, …)

An ensemble solved without an ensemble algorithm runs `EnsembleThreads()` on the CPU and
`EnsembleSerial()` on a device backend (one queue), with `backend` forwarded to every
trajectory's `solve`. Trajectories are the same whichever runs them (independent streams).
"""
function SciMLBase.__solve(prob::SciMLBase.AbstractEnsembleProblem, alg::CPMAlgorithm; backend = CPU(), kwargs...)
    ensemble = backend isa CPU ? EnsembleThreads() : EnsembleSerial()
    return SciMLBase.__solve(prob, alg, ensemble; backend, kwargs...)
end

struct _ReplicaProbFunc{F}
    f::F
end
function (r::_ReplicaProbFunc)(prob, ctx)
    q = r.f(prob, ctx)
    (q.seed == prob.seed && q.replica == prob.replica) || return q
    return remake(q; replica = prob.replica + UInt32(ctx.sim_id), repeat = UInt32(ctx.repeat - 1))
end

"""
    StateIndex(scope, name)

SymbolicIndexingInterface index of the named state array `getfield(st.scope, name)`
(`scope` ∈ `:cell`, `:site`, `:model`). Reading gives the array (a model variable: its
value); writing copies a same-sized array into the live storage, or fills it with a number.
"""
struct StateIndex
    scope::Symbol
    name::Symbol
end
_state_array(st::CPMState, i::StateIndex) = getfield(getfield(st, i.scope), i.name)
function Base.getindex(st::CPMState, i::StateIndex)
    a = _state_array(st, i)
    return i.scope === :model ? only(Array(a)) : a
end
function Base.setindex!(st::CPMState, v, i::StateIndex)
    a = _state_array(st, i)
    if v isa Number
        fill!(a, convert(eltype(a), v))      # a Float64 must not reach a Float32 device array
    else
        size(v) == size(a) ||
            throw(DimensionMismatch("$(i.scope) variable $(i.name) has size $(size(a)); got $(size(v))"))
        copyto!(a, convert(Array{eltype(a)}, v))
    end
    return v
end

"""
Parameter object `p` with parameter `i` set to `v`, converted to the stored type (so the
parameter type, and the compiled code, never change). Symbolic layers add methods for their
parameter objects.
"""
function set_parameter(p::NamedTuple, v, i::Symbol)
    return merge(p, NamedTuple{(i,)}((convert(typeof(getfield(p, i)), v),)))
end

# Setters act on the live state and parameters of an integrator (`integ.u` is a host
# snapshot) and take effect from the next MCS. A problem's parameters are immutable (isbits):
# change them with `remake`.
function SymbolicIndexingInterface.set_state!(integ::PottsIntegrator, v, i::StateIndex)
    KernelAbstractions.synchronize(integ.backend)
    integ.state[i] = v
    # the owner or kind decides which sites are frozen
    (i.scope === :cell && i.name === :kind) && refresh_frozen!(integ)
    return v
end
function SymbolicIndexingInterface.set_parameter!(integ::PottsIntegrator, v, i)
    integ.p = set_parameter(integ.f.sys, integ.p, v, i)
    return nothing
end

"""
    set_parameter(sys, p, v, i)

`set_parameter(p, v, i)` for the model described by `sys` (`CPMFunction.sys`): a symbolic
layer adds a method to validate the value and update parameters derived from `i`.
"""
set_parameter(sys, p, v, i) = set_parameter(p, v, i)
function SymbolicIndexingInterface.set_parameter!(::PottsProblem, v, i)
    throw(ArgumentError("problem parameters are immutable; use `remake(prob; p = [$(repr(i)) => $v])` " *
                        "(or `setp` on an integrator)"))
end

SymbolicIndexingInterface.symbolic_container(f::CPMFunction) = f.sys
SymbolicIndexingInterface.state_values(prob::PottsProblem) = prob.u0
SymbolicIndexingInterface.parameter_values(prob::PottsProblem) = prob.p
SymbolicIndexingInterface.current_time(prob::PottsProblem) = prob.tspan[1]
SymbolicIndexingInterface.is_time_dependent(::PottsProblem) = true
