# SciML interface: problem → init → step!/solve!, with CommonSolve dispatch so that
# `solve(prob, alg)`, `EnsembleProblem`, callbacks-by-integrator and `remake` behave as in
# the rest of SciML. Time is the integer MCS.

const STATUS_NONFINITE = UInt32(1)

"""
    CPMProblem(f::CPMFunction, u0::CPMState, lattice, tspan, p;
               contact = Moore(1), proposal = VonNeumann(1), relations = (;), seed = 0,
               replica = 0, repeat = 0)

A cellular Potts problem. `tspan = (t0, t1)` in MCS. `frozen` (a Bool mask) marks sites
that never change owner and never donate (walls, obstacles); an MCS is one attempt per
mobile site. `spacing` (per-axis lattice spacing,
default 1) is exposed as `ctx.spacing` to field primitives; give it in the model's float
type (Float32 for Metal). `contact` and the named `relations`
(e.g. `(; surface = Moore(1))`) are resolved on `lattice` and exposed to the model's
functions as `ctx.contact`, `ctx.surface`, …. `proposal` is the model's copy neighbourhood,
used by algorithms constructed without one (`SequentialCPM()`). `p` is any isbits parameter object (a `NamedTuple`, or the `PottsParameters`
generated by the symbolic layer); changing it with `remake` never recompiles.
"""
struct CPMProblem{F <: CPMFunction, S <: CPMState, L <: Lattice, R, Q, RS, H, FZ, P} <:
       SciMLBase.AbstractSciMLProblem
    f::F
    u0::S
    lattice::L
    contact::R
    proposal::Q                         # a neighbourhood spec, resolved at `init`
    relations::RS
    spacing::H
    frozen::FZ
    tspan::Tuple{Int, Int}
    p::P
    seed::UInt64
    replica::UInt32
    repeat::UInt32
end

function CPMProblem(f::CPMFunction, u0::CPMState, lattice::Lattice, tspan, p;
        contact = Moore(1), proposal = VonNeumann(1), relations = (;), spacing = nothing,
        frozen = nothing, seed = 0, replica = 0, repeat = 0)
    size(u0.σ) == lattice.dims ||
        throw(ArgumentError("state size $(size(u0.σ)) ≠ lattice $(lattice.dims)"))
    t0, t1 = Int.(tspan)
    0 <= t0 <= t1 <= typemax(UInt32) ||
        throw(ArgumentError("tspan must satisfy 0 ≤ t0 ≤ t1 ≤ 2^32 - 1"))
    any(in((:contact, :proposal, :lattice, :mobility, :spacing)), keys(relations)) &&
        throw(ArgumentError("relation names `contact`, `proposal`, `lattice`, `mobility`, `spacing` are reserved"))
    rs = map(r -> relation(r, lattice), NamedTuple(relations))
    h = spacing === nothing ? nothing : Tuple(spacing)
    h === nothing || (length(h) == ndims(lattice) && all(x -> x > 0, h)) ||
        throw(ArgumentError("spacing must be $(ndims(lattice)) positive numbers"))
    frozen === nothing || size(frozen) == lattice.dims ||
        throw(ArgumentError("frozen mask has size $(size(frozen)), lattice $(lattice.dims)"))
    if lattice.mask !== nothing                     # outside the domain: medium, never mobile
        all(i -> lattice.mask[i] || u0.σ[i] == 0, eachindex(u0.σ)) ||
            throw(ArgumentError("sites outside the lattice domain must belong to the medium (0)"))
        frozen = frozen === nothing ? .!lattice.mask : (frozen .| .!lattice.mask)
    end
    relation(proposal, lattice)                     # validate now; resolved again at `init`
    return CPMProblem(f, u0, lattice, relation(contact, lattice), proposal, rs, h, frozen, (t0, t1), p,
        UInt64(seed), UInt32(replica), UInt32(repeat))
end

# Hooks for the symbolic layer: translate parameter maps / operating points given to
# `remake` into the problem's parameter object and state (identity here).
remake_parameters(sys, prob, p) = p
remake_state(sys, prob, u0) = u0
# the frozen mask of a remade state (models whose mask derives from the state override this)
remake_frozen(sys, prob, u0) = prob.frozen

function SciMLBase.remake(prob::CPMProblem; f = prob.f, u0 = prob.u0, tspan = prob.tspan,
        p = prob.p, seed = prob.seed, replica = prob.replica, repeat = prob.repeat)
    p === prob.p || (p = remake_parameters(f.sys, prob, p))
    frozen = prob.frozen
    if u0 !== prob.u0
        u0 = remake_state(f.sys, prob, u0)
        frozen = remake_frozen(f.sys, prob, u0)
    end
    return CPMProblem(f, u0, prob.lattice, tspan, p; contact = prob.contact,
        proposal = prob.proposal, relations = prob.relations, spacing = prob.spacing, frozen, seed,
        replica, repeat)
end

Base.@kwdef mutable struct PottsStats
    mcs::Int = 0
    attempts::Int = 0
    accepted::Int = -1          # -1: not counted by this algorithm (checkerboard)
    launches::Int = 0
    lifecycle::LifecycleStats = LifecycleStats()
end

"""
    PottsIntegrator

The integrator for a `CPMProblem`. `t` is the current MCS; `integrator.u` returns a host
copy of the state (synchronizing the device only when accessed). `step!` enqueues one MCS
without synchronizing.
"""
mutable struct PottsIntegrator{Alg, Law, P, S, C, LCC, F, KF, Pa, Ctx, B, CB} <: SciMLBase.DEIntegrator{Alg, false, S, Int}
    const prob::P
    const alg::Alg
    const law::Law
    const state::S
    const cache::C
    const lcache::LCC
    const f::F
    const kf::KF
    p::Pa
    const ctx::Ctx
    const backend::B
    const key::RNGKey
    t::Int
    const tstop::Int
    const saveat::Vector{Int}
    const save_start::Bool
    const save_end::Bool
    const saved_t::Vector{Int}
    const saved_u::Vector{Any}
    retcode::SciMLBase.ReturnCode.T
    const stats::PottsStats
    const callbacks::CB             # tuple of DiscreteCallbacks, checked after every MCS
end

# Ensemble statistics: totals over trajectories.
function Base.merge(a::PottsStats, b::PottsStats)
    l = LifecycleStats(; (f => getfield(a.lifecycle, f) + getfield(b.lifecycle, f) for f in fieldnames(LifecycleStats))...)
    return PottsStats(; mcs = a.mcs + b.mcs, attempts = a.attempts + b.attempts,
        accepted = (a.accepted < 0 || b.accepted < 0) ? -1 : a.accepted + b.accepted,
        launches = a.launches + b.launches, lifecycle = l)
end

_to_backend(backend, x) = Adapt.adapt(KernelAbstractions.allocate(backend, Int32, 0) |>
                                      typeof |> _array_adaptor, x)
_array_adaptor(::Type{<:Array}) = Array
_array_adaptor(A::Type) = Base.typename(A).wrapper

"""The copy neighbourhood: the algorithm's if given, else the model's."""
_proposal(alg, prob) = something(alg.proposal, prob.proposal)

function CommonSolve.init(prob::CPMProblem, alg::CPMAlgorithm; backend = CPU(),
        saveat = Int[], save_start = true, save_end = true, checkpoint = nothing,
        callback = nothing)
    if checkpoint !== nothing
        prob = _from_checkpoint(prob, checkpoint)
        integ = init(prob, alg; backend, saveat, save_start, save_end, callback)
        _restore_stats!(integ.stats, checkpoint.stats)
        return integ
    end
    alg isa SequentialCPM && !(backend isa CPU) &&
        throw(ArgumentError("SequentialCPM runs on the host; use CheckerboardCPM on $(typeof(backend))"))
    t0, t1 = prob.tspan
    # SciML convention: a number means "every Δ MCS" from t0 (t0 itself is `save_start`)
    saveat isa Number && (saveat = (t0 + Int(saveat)):Int(saveat):t1)
    outside = filter(t -> !(t0 <= t <= t1), collect(Int, saveat))
    isempty(outside) || @warn "saveat times outside tspan $(prob.tspan) are never reached: $outside"
    lat = prob.lattice
    ctx = (; lattice = _to_backend(backend, lat), proposal = relation(_proposal(alg, prob), lat), contact = prob.contact,
        mobility = _to_backend(backend, mobility(prob.frozen, lat)), prob.relations...)
    prob.spacing === nothing || (ctx = merge(ctx, (; spacing = prob.spacing)))
    _preflight(prob, alg, ctx)
    state = _to_backend(backend, deepcopy(prob.u0))
    p = _to_backend(backend, prob.p)
    cache = alg isa CheckerboardCPM ?
            CheckerboardCache(backend, lat, prob.f, ncells(prob.u0), relation(_proposal(alg, prob), lat)) : nothing
    key = RNGKey(prob.seed, prob.replica, prob.repeat)
    lcache = prob.f.lifecycle === nothing ? nothing :
             LifecycleCache(backend, ndims(lat), ncells(prob.u0))
    integ = PottsIntegrator(prob, alg, _device_law(_law(alg, prob.f), backend), state, cache, lcache, prob.f, device_functions(prob.f), p, ctx, backend, key,
        prob.tspan[1], prob.tspan[2], sort!(collect(Int, saveat)), save_start, save_end,
        Int[], Any[], SciMLBase.ReturnCode.Default, PottsStats(), _callbacks(callback))
    integ.stats.launches += _run_phases(prob.f.phases.at_init, integ.state, integ.p, integ.ctx,
        integ.key, integ.t, integ.backend)
    for cb in integ.callbacks
        cb.initialize(cb, integ.state, integ.t, integ)
    end
    save_start && _save!(integ)
    return integ
end

# SciML callbacks: `DiscreteCallback`s (alone or in a `CallbackSet`) are checked at every
# MCS boundary, after the lifecycle and before saving. `condition(u, t, integrator)` and
# `affect!(integrator)` see the live state (`integrator.state`, on the device for GPU
# backends; `integrator.u` is a host copy). Continuous callbacks have no meaning for an
# MCS clock.
_callbacks(::Nothing) = ()
_callbacks(cb::SciMLBase.DiscreteCallback) = (cb,)
function _callbacks(cb::SciMLBase.CallbackSet)
    isempty(cb.continuous_callbacks) ||
        throw(ArgumentError("continuous callbacks are not supported by Potts integrators (time is the integer MCS); use DiscreteCallback"))
    return cb.discrete_callbacks
end
_callbacks(cb) = throw(ArgumentError("unsupported callback $(typeof(cb)); use DiscreteCallback or CallbackSet"))

function _apply_callbacks!(integ::PottsIntegrator)
    for cb in integ.callbacks
        cb.condition(integ.state, integ.t, integ) && cb.affect!(integ)
    end
    return nothing
end

# No derivative to reset: a callback's changes take effect at the next MCS.
SciMLBase.derivative_discontinuity!(::PottsIntegrator, ::Bool) = nothing
SciMLBase.u_modified!(::PottsIntegrator, ::Bool) = nothing

"""
Reject combinations the algorithm cannot execute correctly. The checkerboard stride comes
from the model's declared footprint, so the declared read radius must cover everything
the kernels read: the proposal source and the contact neighborhood.
"""
function _preflight(prob::CPMProblem, alg::CPMAlgorithm, ctx)
    prob.f.lifecycle === nothing || haskey(prob.u0.cell, :m1) ||
        throw(ArgumentError("a lifecycle needs the moment trackers: add `init_moments(σ, lattice, capacity)` to the cell state"))
    haskey(ctx, :surface) && has_origin(ctx.surface) &&
        throw(ArgumentError("the surface relation must not include the origin"))
    # the pair-energy deltas assume unordered bonds: every offset needs its negation
    for name in (:contact, :surface)
        haskey(ctx, name) && !is_symmetric(getfield(ctx, name)) && throw(ArgumentError(
            "the $name relation is not symmetric (each offset needs its negation with the same " *
            "weight); an asymmetric relation gives a ΔH that is not an energy difference"))
    end
    alg isa CheckerboardCPM || return nothing
    need = max(radius(ctx.contact), maximum(radius, values(prob.relations); init = 0))
    have = first(reach(prob.f.footprint, ctx.proposal))
    have >= need || throw(ArgumentError(
        "CheckerboardCPM: the model declares Footprint(read = $have) but its proposal, " *
        "contact and named relations reach distance $need; pass `footprint = Footprint(read = $need)` " *
        "to CPMFunction"))
    return nothing
end

"""
Host snapshot of the current state: independent of the live state on every backend
(`Adapt.adapt(Array, …)` alone would alias host arrays). Synchronizes the device. The live
device state is `integ.state`.
"""
function current_state(integ::PottsIntegrator)
    KernelAbstractions.synchronize(integ.backend)
    return _snapshot(integ.backend, integ.state)
end
_snapshot(backend, st) = Adapt.adapt(Array, st)
_snapshot(::KernelAbstractions.CPU, st) = deepcopy(st)

function Base.getproperty(integ::PottsIntegrator, name::Symbol)
    name === :u && return current_state(integ)
    name === :ps && return SymbolicIndexingInterface.ParameterIndexingProxy(integ)
    return getfield(integ, name)
end

function _save!(integ::PottsIntegrator)
    push!(integ.saved_t, integ.t)
    push!(integ.saved_u, current_state(integ))
    return nothing
end

function _check_status!(integ::PottsIntegrator)
    integ.alg isa CheckerboardCPM || return integ.retcode
    st = _readback(integ.cache.status)
    st != 0 && (integ.retcode = SciMLBase.ReturnCode.Failure)
    return integ.retcode
end

function CommonSolve.step!(integ::PottsIntegrator)
    integ.retcode == SciMLBase.ReturnCode.Default ||
        throw(ArgumentError("integrator finished with retcode $(integ.retcode)"))
    lat = integ.ctx.lattice
    phases = integ.f.phases
    integ.stats.launches += _run_phases(phases.before_mcs, integ.state, integ.p, integ.ctx,
        integ.key, integ.t, integ.backend)
    if integ.alg isa SequentialCPM
        acc, status = sequential_mcs!(integ.state, integ.kf, integ.p, integ.ctx,
            integ.law, integ.key, integ.t)
        integ.stats.accepted = max(integ.stats.accepted, 0) + acc
        status != 0 && (integ.retcode = SciMLBase.ReturnCode.Failure)
    else
        integ.stats.launches += checkerboard_mcs!(integ.state, integ.cache, integ.kf,
            integ.p, integ.ctx, integ.law, integ.key, integ.t)
    end
    integ.stats.launches += _run_phases(phases.after_mcs, integ.state, integ.p, integ.ctx,
        integ.key, integ.t, integ.backend)
    if integ.f.lifecycle !== nothing
        integ.stats.launches += run_lifecycle!(integ.f.lifecycle, integ.lcache, integ.state,
            integ.p, integ.ctx, integ.key, integ.t, integ.backend, integ.stats.lifecycle)
    end
    integ.stats.launches += _run_phases(phases.end_mcs, integ.state, integ.p, integ.ctx,
        integ.key, integ.t, integ.backend)
    integ.t += 1
    integ.stats.mcs += 1
    integ.stats.attempts += nmobile(integ.ctx.mobility, lat)
    isempty(integ.callbacks) || _apply_callbacks!(integ)
    insorted(integ.t, integ.saveat) && (_check_status!(integ); _save!(integ))
    return integ
end

function CommonSolve.solve!(integ::PottsIntegrator)
    while integ.t < integ.tstop && integ.retcode == SciMLBase.ReturnCode.Default
        step!(integ)
    end
    _check_status!(integ)
    if integ.retcode == SciMLBase.ReturnCode.Default
        integ.retcode = SciMLBase.ReturnCode.Success
    end
    integ.save_end && (isempty(integ.saved_t) || last(integ.saved_t) != integ.t) &&
        _save!(integ)
    for cb in integ.callbacks
        cb.finalize(cb, integ.state, integ.t, integ)
    end
    return PottsSolution(integ)
end

SciMLBase.check_error(integ::PottsIntegrator) = integ.retcode
function SciMLBase.terminate!(integ::PottsIntegrator, retcode = SciMLBase.ReturnCode.Terminated)
    integ.retcode = retcode
    return integ
end

# ---------------------------------------------------------------------------------------

"""Saved states at integer MCS. `sol(t)` looks up a saved MCS exactly (no interpolation)."""
struct PottsSolution{S, P, A} <: SciMLBase.AbstractTimeseriesSolution{S, 1, Vector{S}}
    u::Vector{S}
    t::Vector{Int}
    prob::P
    alg::A
    retcode::SciMLBase.ReturnCode.T
    stats::PottsStats
end

function PottsSolution(integ::PottsIntegrator)
    S = isempty(integ.saved_u) ? Any : typeof(first(integ.saved_u))
    return PottsSolution(convert(Vector{S}, integ.saved_u), copy(integ.saved_t),
        integ.prob, integ.alg, integ.retcode, integ.stats)
end

# Integer indexing is by saved state (`sol[end]` is the final state), not RecursiveArrayTools'
# element indexing: a state is a named collection of arrays, not an array.
Base.getindex(sol::PottsSolution, i::Int) = sol.u[i]
Base.getindex(sol::PottsSolution, i::AbstractVector{<:Integer}) = sol.u[i]
Base.firstindex(sol::PottsSolution) = firstindex(sol.u)
Base.lastindex(sol::PottsSolution) = lastindex(sol.u)

function Base.show(io::IO, ::MIME"text/plain", sol::PottsSolution)
    n = length(sol.t)
    println(io, "PottsSolution: retcode ", sol.retcode, ", ", n, " saved state", n == 1 ? "" : "s",
        ", ", sol.stats.mcs, " MCS")
    print(io, "t: ", n <= 12 ? sol.t : "[$(join(sol.t[1:5], ", ")), …, $(join(sol.t[(end - 4):end], ", "))]")
end
Base.show(io::IO, sol::PottsSolution) =
    print(io, "PottsSolution(", sol.retcode, ", ", length(sol.t), " states)")

function (sol::PottsSolution)(t::Integer)
    i = searchsortedfirst(sol.t, t)
    (i <= length(sol.t) && sol.t[i] == t) ||
        throw(ArgumentError("MCS $t was not saved; saved times are $(sol.t)"))
    return sol.u[i]
end

function _restore_stats!(dst::PottsStats, src::PottsStats)
    dst.mcs, dst.attempts, dst.accepted, dst.launches = src.mcs, src.attempts, src.accepted, src.launches
    for f in fieldnames(LifecycleStats)
        setfield!(dst.lifecycle, f, getfield(src.lifecycle, f))
    end
    return dst
end

# ---------------------------------------------------------------------------------------
# SymbolicIndexingInterface: the symbolic system (if any) is `f.sys`; symbolic layers
# implement the SII queries on it (`sol[x]`, `getp(prob, x)`).

# ---------------------------------------------------------------------------------------
# Ensembles: trajectory `i` is the template with `replica = template.replica + i` and
# `repeat = ctx.repeat - 1` (independent Philox streams, D-005; one compiled model), unless
# the user's `prob_func` already changed the seed or replica.

"""
    EnsembleProblem(prob::CPMProblem; prob_func, output_func, reduction, u_init, safetycopy = false)

A SciML ensemble of Potts runs. Trajectory `i` solves `remake(prob′; replica = prob.replica + i)`,
where `prob′ = prob_func(prob, ctx)` (default: `prob`), so trajectories are independent and
reproducible: trajectory `i` equals `solve(remake(prob; replica = prob.replica + i), alg)`.
"""
function SciMLBase.EnsembleProblem(prob::CPMProblem; prob_func = SciMLBase.DEFAULT_PROB_FUNC,
        safetycopy = false, kwargs...)
    pf = _ReplicaProbFunc(prob_func)
    return invoke(SciMLBase.EnsembleProblem, Tuple{Any}, prob; prob_func = pf, safetycopy, kwargs...)
end

struct _ReplicaProbFunc{F}
    f::F
end
function (r::_ReplicaProbFunc)(prob, ctx)
    q = r.f(prob, ctx)
    (q.seed == prob.seed && q.replica == prob.replica) || return q
    return remake(q; replica = prob.replica + UInt32(ctx.sim_id), repeat = UInt32(ctx.repeat - 1))
end

"""
    StateIndex(scope, name)

SymbolicIndexingInterface index of the named state array `getfield(st.scope, name)`
(`scope` ∈ `:cell`, `:site`, `:model`). Reading gives the array (a model variable: its
value); writing copies a same-sized array into the live storage, or fills it with a number.
"""
struct StateIndex
    scope::Symbol
    name::Symbol
end
_state_array(st::CPMState, i::StateIndex) = getfield(getfield(st, i.scope), i.name)
function Base.getindex(st::CPMState, i::StateIndex)
    a = _state_array(st, i)
    return i.scope === :model ? only(Array(a)) : a
end
function Base.setindex!(st::CPMState, v, i::StateIndex)
    a = _state_array(st, i)
    if v isa Number
        fill!(a, convert(eltype(a), v))      # a Float64 must not reach a Float32 device array
    else
        size(v) == size(a) ||
            throw(DimensionMismatch("$(i.scope) variable $(i.name) has size $(size(a)); got $(size(v))"))
        copyto!(a, convert(Array{eltype(a)}, v))
    end
    return v
end

"""
Parameter object `p` with parameter `i` set to `v`, converted to the stored type (so the
parameter type, and the compiled code, never change). Symbolic layers add methods for their
parameter objects.
"""
function set_parameter(p::NamedTuple, v, i::Symbol)
    return merge(p, NamedTuple{(i,)}((convert(typeof(getfield(p, i)), v),)))
end

# Setters act on the live state and parameters of an integrator (`integ.u` is a host
# snapshot) and take effect from the next MCS. A problem's parameters are immutable (isbits):
# change them with `remake`.
function SymbolicIndexingInterface.set_state!(integ::PottsIntegrator, v, i::StateIndex)
    KernelAbstractions.synchronize(integ.backend)
    integ.state[i] = v
    return v
end
function SymbolicIndexingInterface.set_parameter!(integ::PottsIntegrator, v, i)
    integ.p = set_parameter(integ.f.sys, integ.p, v, i)
    return nothing
end

"""
    set_parameter(sys, p, v, i)

`set_parameter(p, v, i)` for the model described by `sys` (`CPMFunction.sys`): a symbolic
layer adds a method to validate the value and update parameters derived from `i`.
"""
set_parameter(sys, p, v, i) = set_parameter(p, v, i)
function SymbolicIndexingInterface.set_parameter!(::CPMProblem, v, i)
    throw(ArgumentError("problem parameters are immutable; use `remake(prob; p = [$(repr(i)) => $v])` " *
                        "(or `setp` on an integrator)"))
end

SymbolicIndexingInterface.symbolic_container(f::CPMFunction) = f.sys
SymbolicIndexingInterface.state_values(prob::CPMProblem) = prob.u0
SymbolicIndexingInterface.parameter_values(prob::CPMProblem) = prob.p
SymbolicIndexingInterface.current_time(prob::CPMProblem) = prob.tspan[1]
SymbolicIndexingInterface.is_time_dependent(::CPMProblem) = true
