# SciML interface: problem → init → step!/solve!, with CommonSolve dispatch so that
# `solve(prob, alg)`, `EnsembleProblem`, callbacks-by-integrator and `remake` behave as in
# the rest of SciML. Time is the integer MCS.

const STATUS_NONFINITE = UInt32(1)

"""
    CPMProblem(f::CPMFunction, u0::CPMState, lattice, tspan, p;
               contact = Moore(1), seed = 0, replica = 0, repeat = 0)

A cellular Potts problem. `tspan = (t0, t1)` in MCS. `contact` is the contact relation
exposed to the model's functions as `ctx.contact`; the proposal relation belongs to the
algorithm. `p` is any isbits parameter object (a `NamedTuple`, or the `PottsParameters`
generated by the symbolic layer); changing it with `remake` never recompiles.
"""
struct CPMProblem{F <: CPMFunction, S <: CPMState, L <: Lattice, R, P} <:
       SciMLBase.AbstractSciMLProblem
    f::F
    u0::S
    lattice::L
    contact::R
    tspan::Tuple{Int, Int}
    p::P
    seed::UInt64
    replica::UInt32
    repeat::UInt32
end

function CPMProblem(f::CPMFunction, u0::CPMState, lattice::Lattice, tspan, p;
        contact = Moore(1), seed = 0, replica = 0, repeat = 0)
    size(u0.σ) == lattice.dims ||
        throw(ArgumentError("state size $(size(u0.σ)) ≠ lattice $(lattice.dims)"))
    t0, t1 = Int.(tspan)
    0 <= t0 <= t1 <= typemax(UInt32) ||
        throw(ArgumentError("tspan must satisfy 0 ≤ t0 ≤ t1 ≤ 2^32 - 1"))
    return CPMProblem(f, u0, lattice, relation(contact, lattice), (t0, t1), p,
        UInt64(seed), UInt32(replica), UInt32(repeat))
end

function SciMLBase.remake(prob::CPMProblem; f = prob.f, u0 = prob.u0, tspan = prob.tspan,
        p = prob.p, seed = prob.seed, replica = prob.replica, repeat = prob.repeat)
    return CPMProblem(f, u0, prob.lattice, tspan, p; contact = prob.contact, seed,
        replica, repeat)
end

Base.@kwdef mutable struct PottsStats
    mcs::Int = 0
    attempts::Int = 0
    accepted::Int = -1          # -1: not counted by this algorithm (checkerboard)
    launches::Int = 0
end

"""
    PottsIntegrator

The integrator for a `CPMProblem`. `t` is the current MCS; `integrator.u` returns a host
copy of the state (synchronizing the device only when accessed). `step!` enqueues one MCS
without synchronizing.
"""
mutable struct PottsIntegrator{Alg, Law, P, S, C, F, Pa, Ctx, B} <: SciMLBase.DEIntegrator{Alg, false, S, Int}
    const prob::P
    const alg::Alg
    const law::Law
    const state::S
    const cache::C
    const f::F
    p::Pa
    const ctx::Ctx
    const backend::B
    const key::RNGKey
    t::Int
    const tstop::Int
    const saveat::Vector{Int}
    const save_start::Bool
    const save_end::Bool
    const saved_t::Vector{Int}
    const saved_u::Vector{Any}
    retcode::SciMLBase.ReturnCode.T
    const stats::PottsStats
end

_to_backend(backend, x) = Adapt.adapt(KernelAbstractions.allocate(backend, Int32, 0) |>
                                      typeof |> _array_adaptor, x)
_array_adaptor(::Type{<:Array}) = Array
_array_adaptor(A::Type) = Base.typename(A).wrapper

function CommonSolve.init(prob::CPMProblem, alg::CPMAlgorithm; backend = CPU(),
        saveat = Int[], save_start = true, save_end = true)
    alg isa SequentialCPM && !(backend isa CPU) &&
        throw(ArgumentError("SequentialCPM runs on the host; use CheckerboardCPM on $(typeof(backend))"))
    lat = prob.lattice
    ctx = (; lattice = lat, proposal = relation(alg.proposal, lat), contact = prob.contact)
    state = _to_backend(backend, deepcopy(prob.u0))
    p = _to_backend(backend, prob.p)
    cache = alg isa CheckerboardCPM ?
            CheckerboardCache(backend, lat, prob.f, ncells(prob.u0)) : nothing
    key = RNGKey(prob.seed, prob.replica, prob.repeat)
    integ = PottsIntegrator(prob, alg, _device_law(alg.acceptance, backend), state, cache, prob.f, p, ctx, backend, key,
        prob.tspan[1], prob.tspan[2], sort!(collect(Int, saveat)), save_start, save_end,
        Int[], Any[], SciMLBase.ReturnCode.Default, PottsStats())
    save_start && _save!(integ)
    return integ
end

"""Host copy of the current state. Synchronizes the device."""
function current_state(integ::PottsIntegrator)
    KernelAbstractions.synchronize(integ.backend)
    return Adapt.adapt(Array, integ.state)
end

function Base.getproperty(integ::PottsIntegrator, name::Symbol)
    name === :u && return current_state(integ)
    return getfield(integ, name)
end

function _save!(integ::PottsIntegrator)
    push!(integ.saved_t, integ.t)
    push!(integ.saved_u, current_state(integ))
    return nothing
end

function _check_status!(integ::PottsIntegrator)
    integ.alg isa CheckerboardCPM || return integ.retcode
    st = Array(integ.cache.status)[1]
    st != 0 && (integ.retcode = SciMLBase.ReturnCode.Failure)
    return integ.retcode
end

function CommonSolve.step!(integ::PottsIntegrator)
    integ.retcode == SciMLBase.ReturnCode.Default ||
        throw(ArgumentError("integrator finished with retcode $(integ.retcode)"))
    lat = integ.ctx.lattice
    if integ.alg isa SequentialCPM
        acc, status = sequential_mcs!(integ.state, integ.f, integ.p, integ.ctx,
            integ.law, integ.key, integ.t)
        integ.stats.accepted = max(integ.stats.accepted, 0) + acc
        status != 0 && (integ.retcode = SciMLBase.ReturnCode.Failure)
    else
        integ.stats.launches += checkerboard_mcs!(integ.state, integ.cache, integ.f,
            integ.p, integ.ctx, integ.law, integ.key, integ.t)
    end
    integ.t += 1
    integ.stats.mcs += 1
    integ.stats.attempts += nsites(lat)
    insorted(integ.t, integ.saveat) && (_check_status!(integ); _save!(integ))
    return integ
end

function CommonSolve.solve!(integ::PottsIntegrator)
    while integ.t < integ.tstop && integ.retcode == SciMLBase.ReturnCode.Default
        step!(integ)
    end
    _check_status!(integ)
    if integ.retcode == SciMLBase.ReturnCode.Default
        integ.retcode = SciMLBase.ReturnCode.Success
    end
    integ.save_end && (isempty(integ.saved_t) || last(integ.saved_t) != integ.t) &&
        _save!(integ)
    return PottsSolution(integ)
end

SciMLBase.check_error(integ::PottsIntegrator) = integ.retcode
function SciMLBase.terminate!(integ::PottsIntegrator, retcode = SciMLBase.ReturnCode.Terminated)
    integ.retcode = retcode
    return integ
end

# ---------------------------------------------------------------------------------------

"""Saved states at integer MCS. `sol(t)` looks up a saved MCS exactly (no interpolation)."""
struct PottsSolution{S, P, A} <: SciMLBase.AbstractTimeseriesSolution{S, 1, Vector{S}}
    u::Vector{S}
    t::Vector{Int}
    prob::P
    alg::A
    retcode::SciMLBase.ReturnCode.T
    stats::PottsStats
end

function PottsSolution(integ::PottsIntegrator)
    S = isempty(integ.saved_u) ? Any : typeof(first(integ.saved_u))
    return PottsSolution(convert(Vector{S}, integ.saved_u), copy(integ.saved_t),
        integ.prob, integ.alg, integ.retcode, integ.stats)
end

function (sol::PottsSolution)(t::Integer)
    i = searchsortedfirst(sol.t, t)
    (i <= length(sol.t) && sol.t[i] == t) ||
        throw(ArgumentError("MCS $t was not saved; saved times are $(sol.t)"))
    return sol.u[i]
end
