name = "PottsToolkit"
uuid = "e4c62a4c-8889-4cc8-ad3a-75efc86c53b9"
version = "0.2.0"
authors = ["Praneeth Merugu <merugufam@gmail.com>"]

[deps]
CorePotts = "047998c1-3edd-4edf-b561-cee99549c5a6"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ProcessBigraphs = "efcc6515-205e-41e3-b553-f38f05ad529c"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[sources]
CorePotts = {path = "lib/CorePotts"}
ProcessBigraphs = {path = "lib/ProcessBigraphs"}

[compat]
Aqua = "0.8"
CorePotts = "0.2"
KernelAbstractions = "0.9.42"
OrdinaryDiffEqTsit5 = "2"
PrecompileTools = "1"
ProcessBigraphs = "0.6"
SciMLBase = "3"
SHA = "0.7"
StaticArrays = "1"
Test = "1"
TOML = "1"
Unitful = "1"
julia = "1.12"

[weakdeps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
PottsToolkitUnitfulExt = "Unitful"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Aqua", "KernelAbstractions", "Test", "TOML", "Unitful"]

[workspace]
projects = ["integration", "lib/CorePotts", "lib/MakiePotts", "lib/ProcessBigraphs"]
