# Reviewed environment data is isolated from the hardware-neutral provider and
# lowering code. A new row requires repository evidence and LW-R1 review.

const _REVIEWED_BACKEND_PROBES = (
    (
        backend_package_uuid =
            "dde4c033-4e86-420c-a63e-0dd931031962",
        backend_package_version = v"1.10.0",
        backend_module = "Metal.MetalKernels",
        backend_type = "MetalBackend",
        current_device = :device,
        device_properties = (
            :name,
            :registryID,
            :location,
            :locationNumber,
            :lowPower,
            :headless,
            :removable,
            :hasUnifiedMemory,
        ),
        runtime_functions = (
            :macos_version,
            :darwin_version,
            :metal_target,
            :air_target,
            :metallib_target,
        ),
        preferences = (
            "default_storage",
            "label_resources",
            "nonblocking_synchronization",
            "command_batching",
            "command_batching_ops",
            "command_batching_bytes",
            "command_batching_inflight",
        ),
    ),
)

const _REVIEWED_BACKEND_ENVIRONMENTS = (
    (
        julia = v"1.12.6",
        kernelabstractions = v"0.9.42",
        atomix = v"1.1.3",
        adapt = v"4.7.0",
        backend_package_uuid =
            "63c18a36-062a-441e-b654-da1e3ab1ce7c",
        backend_package_version = v"0.9.42",
        backend_module = "KernelAbstractions",
        backend_type = "CPU",
        device_type = "Int64",
        device_value = "1",
        device_identity = (
            source = :kernelabstractions,
            type = "Int64",
            value = "1",
        ),
        runtime_identity = (;),
        provider_preferences = (;),
        kernel = :Darwin,
        architecture = :aarch64,
        machine = "arm64-apple-darwin24.0.0",
        cpu = "apple-m1",
        word_size = 64,
    ),
    (
        julia = v"1.12.6",
        kernelabstractions = v"0.9.42",
        atomix = v"1.1.3",
        adapt = v"4.7.0",
        backend_package_uuid =
            "dde4c033-4e86-420c-a63e-0dd931031962",
        backend_package_version = v"1.10.0",
        backend_module = "Metal.MetalKernels",
        backend_type = "MetalBackend",
        device_type = "Int64",
        device_value = "1",
        device_identity = (
            source = :reviewed_backend_probe,
            name = "Apple M1 Pro",
            registryID = UInt64(0x000000010000099d),
            location = "Metal.MTL.MTLDeviceLocationBuiltIn",
            locationNumber = UInt64(0),
            lowPower = false,
            headless = false,
            removable = false,
            hasUnifiedMemory = true,
        ),
        runtime_identity = (
            macos_version = v"15.6.1",
            darwin_version = v"24.6.0",
            metal_target = v"3.2.0",
            air_target = v"2.7.0",
            metallib_target = v"1.2.8",
        ),
        provider_preferences = (
            default_storage = nothing,
            label_resources = nothing,
            nonblocking_synchronization = nothing,
            command_batching = nothing,
            command_batching_ops = nothing,
            command_batching_bytes = nothing,
            command_batching_inflight = nothing,
        ),
        kernel = :Darwin,
        architecture = :aarch64,
        machine = "arm64-apple-darwin24.0.0",
        cpu = "apple-m1",
        word_size = 64,
    ),
)
