using Test
using CorePotts

@testset "CorePotts" begin
    include("test_logical_initialization.jl")
    include("test_logical_lifecycle.jl")
    include("test_logical_state.jl")
    include("test_rng_semantics.jl")
    include("test_execution_contracts.jl")
    include("test_reference_engine.jl")
    include("test_scientific_protocols.jl")
    include("test_phase13_contract_versions.jl")
    include("test_phase13_quality_gates.jl")
    include("test_state_semantics.jl")
    include("test_phase8_protocols.jl")
    include("test_phase8_lifecycle.jl")
    include("test_phase8_persistence.jl")
    include("test_phase9_sciml_interface.jl")
    include("test_topology_abstractions.jl")
    include("test_cartesian_relations.jl")
    include("test_proposal_acceptance.jl")
    include("test_scientific_hamiltonians.jl")
    include("test_scientific_transactions.jl")
    include("test_scientific_fields.jl")
    include("test_scientific_queries_connectivity.jl")
    include("test_scientific_focal_points.jl")
    include("test_scientific_elongation.jl")
    include("test_scientific_inner_loop.jl")
    include("test_phase10_extension_protocol.jl")
    include("test_scientific_mechanics.jl")
    include("test_sequential_algorithms.jl")
    include("test_phase14_dynamic_state.jl")
    include("test_phase14_relationship_processes.jl")
    include("test_phase14_contact_relationships.jl")
include("test_phase14_polarity_force.jl")
include("test_phase14_vector_boundary_potential.jl")
include("test_phase14_bounded_observations.jl")
    include("test_phase14_cell_history.jl")
include("test_phase14_history_polarity.jl")
include("test_phase16_native_fields.jl")
    include("test_phase16_process_bigraph_adapter.jl")
    include("test_checkerboard_algorithms.jl")
    include("test_tiled_checkerboard.jl")
    include("test_lottery_algorithms.jl")
    include("test_scientific_device_path.jl")
end
