[deps]
CorePotts = "047998c1-3edd-4edf-b561-cee99549c5a6"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
MakiePotts = "95794c00-c762-4965-bf31-de18bcca2bc9"
PottsToolkit = "e4c62a4c-8889-4cc8-ad3a-75efc86c53b9"

[sources]
CorePotts = {path = "../lib/CorePotts"}
MakiePotts = {path = "../lib/MakiePotts"}
PottsToolkit = {path = ".."}

[compat]
Documenter = "1"
julia = "1.12.6"
