#!/usr/bin/env julia

using TOML

const ROOT = normpath(joinpath(@__DIR__, ".."))
const OUTPUT = joinpath(
    ROOT, "lib", "ProcessBigraphs", "docs", "src",
    "phase16-capabilities.md")

function cell(value)
    value isa AbstractVector && return join(string.(value), ", ")
    return replace(string(value), "|" => "\\|")
end

function render_capabilities()
    entry = TOML.parsefile(joinpath(
        ROOT, "spec", "process-bigraph-phase16-entry-v1.toml"))
    matrix = TOML.parsefile(joinpath(
        ROOT, "spec", "process-bigraph-phase16-backend-matrix-v1.toml"))
    api = TOML.parsefile(joinpath(
        ROOT, "spec", "process-bigraph-phase16-api-v1.toml"))
    models = TOML.parsefile(joinpath(
        ROOT, "spec", "process-bigraph-phase16-model-scope-v1.toml"))
    ledger = TOML.parsefile(joinpath(
        ROOT, "spec", "process-bigraph-phase16-qualification-v1.toml"))

    io = IOBuffer()
    println(io, "# Phase 16 capability and limitation matrix")
    println(io)
    println(io, "<!-- Generated by scripts/process-bigraph-phase16-docs.jl. -->")
    println(io)
    println(io, "- Implementation state: `$(entry["implementation_status"])`")
    println(io, "- Current package version: `$(entry["current_package_version"])`")
    println(io, "- Target internal-beta version: `$(entry["target_package_version"])`")
    println(io, "- Internal beta: `$(entry["internal_beta"])`")
    println(io, "- Public release: `$(entry["public_release"])`")
    println(io)
    println(io, "ProcessBigraphs owns when and why computation occurs. Selected solvers and CPM kernels own how authorized heavy computation occurs.")
    println(io)
    println(io, "## Backend envelopes")
    println(io)
    println(io, "| Envelope | Adapter | CPU | Metal | ROCm | CUDA | Precision |")
    println(io, "|---|---|---:|---:|---:|---:|---|")
    for row in matrix["envelopes"]
        println(io,
            "| `$(row["id"])` | `$(row["adapter"])` | $(row["CPU"]) | ",
            "$(row["Metal"]) | $(row["ROCm"]) | $(row["CUDA"]) | ",
            "$(cell(row["precision"])) |")
    end
    println(io)
    println(io, "## API families")
    println(io)
    println(io, "| Family | Gate | Status | Admission rule |")
    println(io, "|---|---|---:|---|")
    for row in api["families"]
        println(io,
            "| `$(row["id"])` | $(row["subgate"]) | $(row["status"]) | ",
            "$(cell(row["export_rule"])) |")
    end
    println(io)
    println(io,
        "The internal-beta allowlist contains ",
        "$(length(api["planned_internal_beta_exports"])) exported names and ",
        "$(length(api["planned_public_unexported"])) qualified-name expert types or codecs.")
    println(io)
    println(io, "## Runnable model scope")
    println(io)
    println(io, "| Model | Status | Required bounded target | Excluded analysis |")
    println(io, "|---|---:|---|---|")
    for row in models["models"]
        target = haskey(row, "required_dimension") ?
            join(row["required_dimension"], "×") :
            "scenario $(row["required_scenario"]), simulation $(row["required_source_simulation"])"
        println(io,
            "| `$(row["id"])` | $(row["status"]) | $(target) | ",
            "$(cell(row["excluded"])) |")
    end
    println(io)
    println(io, "## Open qualification rows")
    println(io)
    open_rows = [
        row for row in ledger["requirements"]
        if row["status"] != "qualified"
    ]
    if isempty(open_rows)
        println(io, "None.")
    else
        println(io, "| Row | Gate | Status | Requirement |")
        println(io, "|---|---|---:|---|")
        for row in open_rows
            println(io,
                "| `$(row["id"])` | $(row["subgate"]) | $(row["status"]) | ",
                "$(cell(row["title"])) |")
        end
    end
    println(io)
    println(io, "## Explicitly excluded API claims")
    println(io)
    for item in api["excluded_api_claims"]
        println(io, "- $(item)")
    end
    println(io)
    println(io, "## Explicit Phase 16 scope exclusions")
    println(io)
    for item in entry["scope"]["excluded"]
        println(io, "- `$(item)`")
    end
    return String(take!(io))
end

content = render_capabilities()
if ARGS == ["--write"]
    mkpath(dirname(OUTPUT))
    open(OUTPUT, "w") do io
        write(io, content)
    end
    println("Wrote $(relpath(OUTPUT, ROOT))")
elseif isempty(ARGS) || ARGS == ["--check"]
    isfile(OUTPUT) ||
        error("generated capability page is missing: $(relpath(OUTPUT, ROOT))")
    read(OUTPUT, String) == content ||
        error("generated Phase 16 capability page is stale; run this script with --write")
    println("ProcessBigraphs Phase 16 generated capability page is current.")
else
    error("usage: process-bigraph-phase16-docs.jl [--check|--write]")
end
