[deps]
CorePotts = "047998c1-3edd-4edf-b561-cee99549c5a6"
PottsToolkit = "e4c62a4c-8889-4cc8-ad3a-75efc86c53b9"

[sources]
CorePotts = {path = "../lib/CorePotts"}
KernelIntrinsics = {url = "https://github.com/PraneethMerugu/KernelIntrinsics.jl.git", rev = "b3a02b6e80f0839082a02f1838af7e10e992062c"}
PottsToolkit = {path = ".."}

[compat]
julia = "1.12"

[extras]
KernelIntrinsics = "f9588fbb-d238-4998-b15a-468e8766d49a"
